<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Classes.php');
	include_once(__DIR__ . '/Classes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Classes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Classes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Classes`.`id`" => "id",
		"`Classes`.`Class`" => "Class",
		"`Classes`.`Students_Number`" => "Students_Number",
		"`Classes`.`Type`" => "Type",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Classes`.`id`',
		2 => 2,
		3 => '`Classes`.`Students_Number`',
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Classes`.`id`" => "id",
		"`Classes`.`Class`" => "Class",
		"`Classes`.`Students_Number`" => "Students_Number",
		"`Classes`.`Type`" => "Type",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Classes`.`id`" => "ID",
		"`Classes`.`Class`" => "&#932;&#956;&#942;&#956;&#945;",
		"`Classes`.`Students_Number`" => "&#913;&#961;&#953;&#952;&#956;&#972;&#962; &#924;&#945;&#952;&#951;&#964;&#974;&#957;",
		"`Classes`.`Type`" => "&#924;&#959;&#957;&#972;/&#916;&#953;&#960;&#955;&#972;",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Classes`.`id`" => "id",
		"`Classes`.`Class`" => "Class",
		"`Classes`.`Students_Number`" => "Students_Number",
		"`Classes`.`Type`" => "Type",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Classes` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Classes_view.php';
	$x->TableTitle = '&#932;&#956;&#942;&#956;&#945;&#964;&#945;';
	$x->TableIcon = 'resources/table_icons/blackboard_empty.png';
	$x->PrimaryKey = '`Classes`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['&#932;&#956;&#942;&#956;&#945;', '&#913;&#961;&#953;&#952;&#956;&#972;&#962; &#924;&#945;&#952;&#951;&#964;&#974;&#957;', '&#924;&#959;&#957;&#972;/&#916;&#953;&#960;&#955;&#972;', ];
	$x->ColFieldName = ['Class', 'Students_Number', 'Type', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Classes_templateTV.html';
	$x->SelectedTemplate = 'templates/Classes_templateTVS.html';
	$x->TemplateDV = 'templates/Classes_templateDV.html';
	$x->TemplateDVP = 'templates/Classes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Classes_init
	$render = true;
	if(function_exists('Classes_init')) {
		$args = [];
		$render = Classes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Classes_header
	$headerCode = '';
	if(function_exists('Classes_header')) {
		$args = [];
		$headerCode = Classes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Classes_footer
	$footerCode = '';
	if(function_exists('Classes_footer')) {
		$args = [];
		$footerCode = Classes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
