<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Documents_tamplates.php');
	include_once(__DIR__ . '/Documents_tamplates_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Documents_tamplates');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Documents_tamplates';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Documents_tamplates`.`id`" => "id",
		"`Documents_tamplates`.`title`" => "title",
		"`Documents_tamplates`.`hex_doc`" => "hex_doc",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Documents_tamplates`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Documents_tamplates`.`id`" => "id",
		"`Documents_tamplates`.`title`" => "title",
		"`Documents_tamplates`.`hex_doc`" => "hex_doc",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Documents_tamplates`.`id`" => "ID",
		"`Documents_tamplates`.`title`" => "&#932;&#943;&#964;&#955;&#959;&#962;",
		"`Documents_tamplates`.`hex_doc`" => "Hex doc",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Documents_tamplates`.`id`" => "id",
		"`Documents_tamplates`.`title`" => "title",
		"`Documents_tamplates`.`hex_doc`" => "hex_doc",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Documents_tamplates` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Documents_tamplates_view.php';
	$x->TableTitle = '&#928;&#961;&#972;&#964;&#965;&#960;&#945; &#917;&#947;&#947;&#961;&#940;&#966;&#969;&#957;';
	$x->TableIcon = 'resources/table_icons/align_above.png';
	$x->PrimaryKey = '`Documents_tamplates`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['&#932;&#943;&#964;&#955;&#959;&#962;', ];
	$x->ColFieldName = ['title', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Documents_tamplates_templateTV.html';
	$x->SelectedTemplate = 'templates/Documents_tamplates_templateTVS.html';
	$x->TemplateDV = 'templates/Documents_tamplates_templateDV.html';
	$x->TemplateDVP = 'templates/Documents_tamplates_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Documents_tamplates_init
	$render = true;
	if(function_exists('Documents_tamplates_init')) {
		$args = [];
		$render = Documents_tamplates_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Documents_tamplates_header
	$headerCode = '';
	if(function_exists('Documents_tamplates_header')) {
		$args = [];
		$headerCode = Documents_tamplates_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Documents_tamplates_footer
	$footerCode = '';
	if(function_exists('Documents_tamplates_footer')) {
		$args = [];
		$footerCode = Documents_tamplates_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
