<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Examinations.php');
	include_once(__DIR__ . '/Examinations_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Examinations');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Examinations';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Examinations`.`id`" => "id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Examinations`.`id`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Examinations`.`id`" => "id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Examinations`.`id`" => "ID",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Examinations`.`id`" => "id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Examinations` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Examinations_view.php';
	$x->TableTitle = '&#917;&#957;&#948;&#959;&#963;&#967;&#959;&#955;&#953;&#954;&#941;&#962; &#917;&#958;&#949;&#964;&#940;&#963;&#949;&#953;&#962;';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Examinations`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['ID', ];
	$x->ColFieldName = ['id', ];
	$x->ColNumber  = [1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Examinations_templateTV.html';
	$x->SelectedTemplate = 'templates/Examinations_templateTVS.html';
	$x->TemplateDV = 'templates/Examinations_templateDV.html';
	$x->TemplateDVP = 'templates/Examinations_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Examinations_init
	$render = true;
	if(function_exists('Examinations_init')) {
		$args = [];
		$render = Examinations_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Examinations_header
	$headerCode = '';
	if(function_exists('Examinations_header')) {
		$args = [];
		$headerCode = Examinations_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Examinations_footer
	$footerCode = '';
	if(function_exists('Examinations_footer')) {
		$args = [];
		$footerCode = Examinations_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
