<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Incoming_Files.php');
	include_once(__DIR__ . '/Incoming_Files_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Incoming_Files');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Incoming_Files';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Incoming_Files`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Protocol1`.`serial_number`) || CHAR_LENGTH(if(`Protocol1`.`receipt_date`,date_format(`Protocol1`.`receipt_date`,'%d-%m-%Y'),'')), CONCAT_WS('',   `Protocol1`.`serial_number`, '/', if(`Protocol1`.`receipt_date`,date_format(`Protocol1`.`receipt_date`,'%d-%m-%Y'),'')), '') /* &#913;&#961;. &#928;&#961;&#969;&#964;&#959;&#954;&#972;&#955;&#955;&#959;&#965; */" => "protocol_id",
		"`Incoming_Files`.`title`" => "title",
		"`Incoming_Files`.`file`" => "file",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Incoming_Files`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Incoming_Files`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Protocol1`.`serial_number`) || CHAR_LENGTH(if(`Protocol1`.`receipt_date`,date_format(`Protocol1`.`receipt_date`,'%d-%m-%Y'),'')), CONCAT_WS('',   `Protocol1`.`serial_number`, '/', if(`Protocol1`.`receipt_date`,date_format(`Protocol1`.`receipt_date`,'%d-%m-%Y'),'')), '') /* &#913;&#961;. &#928;&#961;&#969;&#964;&#959;&#954;&#972;&#955;&#955;&#959;&#965; */" => "protocol_id",
		"`Incoming_Files`.`title`" => "title",
		"`Incoming_Files`.`file`" => "file",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Incoming_Files`.`id`" => "ID",
		"`Incoming_Files`.`title`" => "&#920;&#941;&#956;&#945;",
		"`Incoming_Files`.`file`" => "&#913;&#961;&#967;&#949;&#943;&#959;",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Incoming_Files`.`id`" => "id",
		"`Incoming_Files`.`title`" => "title",
		"`Incoming_Files`.`file`" => "file",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['protocol_id' => '&#913;&#961;. &#928;&#961;&#969;&#964;&#959;&#954;&#972;&#955;&#955;&#959;&#965;', ];

	$x->QueryFrom = "`Incoming_Files` LEFT JOIN `Protocol` as Protocol1 ON `Protocol1`.`id`=`Incoming_Files`.`protocol_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Incoming_Files_view.php';
	$x->TableTitle = '&#917;&#953;&#963;&#949;&#961;&#967;&#972;&#956;&#949;&#957;&#945;';
	$x->TableIcon = 'resources/table_icons/align_left.png';
	$x->PrimaryKey = '`Incoming_Files`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['&#913;&#961;. &#928;&#961;&#969;&#964;&#959;&#954;&#972;&#955;&#955;&#959;&#965;', '&#920;&#941;&#956;&#945;', '&#913;&#961;&#967;&#949;&#943;&#959;', ];
	$x->ColFieldName = ['protocol_id', 'title', 'file', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Incoming_Files_templateTV.html';
	$x->SelectedTemplate = 'templates/Incoming_Files_templateTVS.html';
	$x->TemplateDV = 'templates/Incoming_Files_templateDV.html';
	$x->TemplateDVP = 'templates/Incoming_Files_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Incoming_Files_init
	$render = true;
	if(function_exists('Incoming_Files_init')) {
		$args = [];
		$render = Incoming_Files_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Incoming_Files_header
	$headerCode = '';
	if(function_exists('Incoming_Files_header')) {
		$args = [];
		$headerCode = Incoming_Files_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Incoming_Files_footer
	$footerCode = '';
	if(function_exists('Incoming_Files_footer')) {
		$args = [];
		$footerCode = Incoming_Files_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
