<?php

// Data functions (insert, update, delete, form) for table Lessons

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Lessons_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Lessons');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Class' => Request::val('Class', ''),
		'Name' => Request::val('Name', ''),
		'Type' => Request::val('Type', ''),
		'Hours' => Request::val('Hours', ''),
		'A_assignment' => br2nl(Request::val('A_assignment', '')),
		'B_assignment' => br2nl(Request::val('B_assignment', '')),
		'C_assignment' => br2nl(Request::val('C_assignment', '')),
		'bank' => Request::checkBox('bank', '0'),
	];

	if($data['Class'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#932;&#940;&#958;&#951;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Name'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#924;&#940;&#952;&#951;&#956;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Type'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#920;&#949;&#969;&#961;&#943;&#945;/&#917;&#961;&#947;&#945;&#963;&#964;&#942;&#961;&#953;&#959;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Hours'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#911;&#961;&#949;&#962;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Lessons_before_insert
	if(function_exists('Lessons_before_insert')) {
		$args = [];
		if(!Lessons_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Lessons', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Lessons', $recID, calculated_fields()['Lessons']);

	// hook: Lessons_after_insert
	if(function_exists('Lessons_after_insert')) {
		$res = sql("SELECT * FROM `Lessons` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Lessons_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Lessons', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Lessons_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Lessons_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Lessons_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Lessons', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Lessons_before_delete
	if(function_exists('Lessons_before_delete')) {
		$args = [];
		if(!Lessons_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Assignments
	$res = sql("SELECT `id` FROM `Lessons` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Assignments` WHERE `LessonID`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Assignments', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Assignments', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Lessons_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Lessons_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Lessons` WHERE `id`='{$selected_id}'", $eo);

	// hook: Lessons_after_delete
	if(function_exists('Lessons_after_delete')) {
		$args = [];
		Lessons_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Lessons' AND `pkValue`='{$selected_id}'", $eo);
}

function Lessons_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Lessons', $selected_id, 'edit')) return false;

	$data = [
		'Class' => Request::val('Class', ''),
		'Name' => Request::val('Name', ''),
		'Type' => Request::val('Type', ''),
		'Hours' => Request::val('Hours', ''),
		'A_assignment' => br2nl(Request::val('A_assignment', '')),
		'B_assignment' => br2nl(Request::val('B_assignment', '')),
		'C_assignment' => br2nl(Request::val('C_assignment', '')),
		'bank' => Request::checkBox('bank', ''),
	];

	if($data['Class'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#932;&#940;&#958;&#951;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Name'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#924;&#940;&#952;&#951;&#956;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Type'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#920;&#949;&#969;&#961;&#943;&#945;/&#917;&#961;&#947;&#945;&#963;&#964;&#942;&#961;&#953;&#959;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Hours'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#911;&#961;&#949;&#962;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Lessons', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Lessons_before_update
	if(function_exists('Lessons_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Lessons_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Lessons', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Lessons_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Lessons', $data['selectedID'], calculated_fields()['Lessons']);

	// hook: Lessons_after_update
	if(function_exists('Lessons_after_update')) {
		$res = sql("SELECT * FROM `Lessons` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Lessons_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Lessons', $selected_id);
}

function Lessons_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Lessons');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Class
	$combo_Class = new Combo;
	$combo_Class->ListType = 0;
	$combo_Class->MultipleSeparator = ', ';
	$combo_Class->ListBoxHeight = 10;
	$combo_Class->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Lessons.Class.csv')) {
		$Class_data = addslashes(implode('', @file(__DIR__ . '/hooks/Lessons.Class.csv')));
		$combo_Class->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Class_data))));
		$combo_Class->ListData = $combo_Class->ListItem;
	} else {
		$combo_Class->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("&#913;;;&#914;;;&#915;"))));
		$combo_Class->ListData = $combo_Class->ListItem;
	}
	$combo_Class->SelectName = 'Class';
	$combo_Class->AllowNull = false;
	// combobox: Type
	$combo_Type = new Combo;
	$combo_Type->ListType = 0;
	$combo_Type->MultipleSeparator = ', ';
	$combo_Type->ListBoxHeight = 10;
	$combo_Type->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Lessons.Type.csv')) {
		$Type_data = addslashes(implode('', @file(__DIR__ . '/hooks/Lessons.Type.csv')));
		$combo_Type->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Type_data))));
		$combo_Type->ListData = $combo_Type->ListItem;
	} else {
		$combo_Type->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("&#915;&#917;&#925;&#921;&#922;&#919;&#931; &#928;&#913;&#921;&#916;&#917;&#921;&#913;&#931;;;&#920;&#917;&#937;&#929;&#921;&#913;;;&#917;&#929;&#915;&#913;&#931;&#932;&#919;&#929;&#921;&#927;"))));
		$combo_Type->ListData = $combo_Type->ListItem;
	}
	$combo_Type->SelectName = 'Type';
	$combo_Type->AllowNull = false;

	if($selected_id) {
		if(!check_record_permission('Lessons', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Lessons', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Lessons', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Lessons` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Lessons_view.php', false);
		}
		$combo_Class->SelectedData = $row['Class'];
		$combo_Type->SelectedData = $row['Type'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Class->SelectedText = (isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_Type->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_Class->Render();
	$combo_Type->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Lessons_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Lessons_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', '&#924;&#940;&#952;&#951;&#956;&#945;', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Lessons_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Lessons_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Lessons_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Class').replaceWith('<div class=\"form-control-static\" id=\"Class\">' + (jQuery('#Class').val() || '') + '</div>'); jQuery('#Class-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Name').replaceWith('<div class=\"form-control-static\" id=\"Name\">' + (jQuery('#Name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Type').replaceWith('<div class=\"form-control-static\" id=\"Type\">' + (jQuery('#Type').val() || '') + '</div>'); jQuery('#Type-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Hours').replaceWith('<div class=\"form-control-static\" id=\"Hours\">' + (jQuery('#Hours').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#A_assignment').replaceWith('<div class=\"form-control-static\" id=\"A_assignment\">' + (jQuery('#A_assignment').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#B_assignment').replaceWith('<div class=\"form-control-static\" id=\"B_assignment\">' + (jQuery('#B_assignment').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#C_assignment').replaceWith('<div class=\"form-control-static\" id=\"C_assignment\">' + (jQuery('#C_assignment').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#bank').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Class)%%>', $combo_Class->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Class)%%>', $combo_Class->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Type)%%>', $combo_Type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Type)%%>', $combo_Type->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Class)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Hours)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(NameTypeHours)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(A_assignment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(B_assignment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(C_assignment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(bank)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Class)%%>', safe_html($urow['Class']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Class)%%>', html_attr($row['Class']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Class)%%>', urlencode($urow['Class']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', safe_html($urow['Name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', html_attr($row['Name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode($urow['Name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Type)%%>', safe_html($urow['Type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Type)%%>', html_attr($row['Type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Type)%%>', urlencode($urow['Type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Hours)%%>', safe_html($urow['Hours']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Hours)%%>', html_attr($row['Hours']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hours)%%>', urlencode($urow['Hours']), $templateCode);
		$templateCode = str_replace('<%%VALUE(NameTypeHours)%%>', safe_html($urow['NameTypeHours']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(NameTypeHours)%%>', urlencode($urow['NameTypeHours']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(A_assignment)%%>', safe_html($urow['A_assignment']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(A_assignment)%%>', safe_html($urow['A_assignment'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(A_assignment)%%>', urlencode($urow['A_assignment']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(B_assignment)%%>', safe_html($urow['B_assignment']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(B_assignment)%%>', safe_html($urow['B_assignment'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(B_assignment)%%>', urlencode($urow['B_assignment']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(C_assignment)%%>', safe_html($urow['C_assignment']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(C_assignment)%%>', safe_html($urow['C_assignment'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(C_assignment)%%>', urlencode($urow['C_assignment']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(bank)%%>', ($row['bank'] ? "checked" : ""), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Class)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Class)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Hours)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hours)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(NameTypeHours)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(NameTypeHours)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(A_assignment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(A_assignment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(B_assignment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(B_assignment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(C_assignment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(C_assignment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(bank)%%>', '', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Lessons');
	if($selected_id) {
		$jdata = get_joined_record('Lessons', $selected_id);
		if($jdata === false) $jdata = get_defaults('Lessons');
		$rdata = $row;
	}
	$templateCode .= loadView('Lessons-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Lessons_dv
	if(function_exists('Lessons_dv')) {
		$args = [];
		Lessons_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}