<?php

// Data functions (insert, update, delete, form) for table Outcoming_Files

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Outcoming_Files_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Outcoming_Files');
	if(!$arrPerm['insert']) return false;

	$data = [
		'protocol_id' => Request::lookup('protocol_id', ''),
		'title' => Request::val('title', ''),
		'doc_template_id' => Request::lookup('doc_template_id', ''),
		'hex_doc' => br2nl(Request::val('hex_doc', '')),
		'file' => Request::fileUpload('file', [
			'maxSize' => 5120000,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Outcoming_Files', 'file', Request::val('SelectedID'));
			},
		]),
	];

	if($data['title'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#920;&#941;&#956;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Outcoming_Files_before_insert
	if(function_exists('Outcoming_Files_before_insert')) {
		$args = [];
		if(!Outcoming_Files_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Outcoming_Files', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Outcoming_Files', $recID, calculated_fields()['Outcoming_Files']);

	// hook: Outcoming_Files_after_insert
	if(function_exists('Outcoming_Files_after_insert')) {
		$res = sql("SELECT * FROM `Outcoming_Files` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Outcoming_Files_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Outcoming_Files', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Outcoming_Files_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Outcoming_Files_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Outcoming_Files_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Outcoming_Files', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Outcoming_Files_before_delete
	if(function_exists('Outcoming_Files_before_delete')) {
		$args = [];
		if(!Outcoming_Files_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Outcoming_Files` WHERE `id`='{$selected_id}'", $eo);

	// hook: Outcoming_Files_after_delete
	if(function_exists('Outcoming_Files_after_delete')) {
		$args = [];
		Outcoming_Files_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Outcoming_Files' AND `pkValue`='{$selected_id}'", $eo);
}

function Outcoming_Files_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Outcoming_Files', $selected_id, 'edit')) return false;

	$data = [
		'protocol_id' => Request::lookup('protocol_id', ''),
		'title' => Request::val('title', ''),
		'doc_template_id' => Request::lookup('doc_template_id', ''),
		'hex_doc' => br2nl(Request::val('hex_doc', '')),
		'file' => Request::fileUpload('file', [
			'maxSize' => 5120000,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Outcoming_Files', 'file', $selected_id);
			},
		]),
	];

	if($data['title'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#920;&#941;&#956;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Outcoming_Files', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Outcoming_Files_before_update
	if(function_exists('Outcoming_Files_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Outcoming_Files_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Outcoming_Files', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Outcoming_Files_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Outcoming_Files', $data['selectedID'], calculated_fields()['Outcoming_Files']);

	// hook: Outcoming_Files_after_update
	if(function_exists('Outcoming_Files_after_update')) {
		$res = sql("SELECT * FROM `Outcoming_Files` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Outcoming_Files_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Outcoming_Files', $selected_id);
}

function Outcoming_Files_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Outcoming_Files');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_protocol_id = Request::val('filterer_protocol_id');
	$filterer_doc_template_id = Request::val('filterer_doc_template_id');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: protocol_id
	$combo_protocol_id = new DataCombo;
	// combobox: doc_template_id
	$combo_doc_template_id = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('Outcoming_Files', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Outcoming_Files', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Outcoming_Files', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Outcoming_Files` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Outcoming_Files_view.php', false);
		}
		$combo_protocol_id->SelectedData = $row['protocol_id'];
		$combo_doc_template_id->SelectedData = $row['doc_template_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_protocol_id->SelectedData = $filterer_protocol_id;
		$combo_doc_template_id->SelectedData = $filterer_doc_template_id;
	}
	$combo_protocol_id->HTML = '<span id="protocol_id-container' . $rnd1 . '"></span><input type="hidden" name="protocol_id" id="protocol_id' . $rnd1 . '" value="' . html_attr($combo_protocol_id->SelectedData) . '">';
	$combo_protocol_id->MatchText = '<span id="protocol_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="protocol_id" id="protocol_id' . $rnd1 . '" value="' . html_attr($combo_protocol_id->SelectedData) . '">';
	$combo_doc_template_id->HTML = '<span id="doc_template_id-container' . $rnd1 . '"></span><input type="hidden" name="doc_template_id" id="doc_template_id' . $rnd1 . '" value="' . html_attr($combo_doc_template_id->SelectedData) . '">';
	$combo_doc_template_id->MatchText = '<span id="doc_template_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="doc_template_id" id="doc_template_id' . $rnd1 . '" value="' . html_attr($combo_doc_template_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_protocol_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['protocol_id'] : htmlspecialchars($filterer_protocol_id, ENT_QUOTES)); ?>"};
		AppGini.current_doc_template_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['doc_template_id'] : htmlspecialchars($filterer_doc_template_id, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(protocol_id_reload__RAND__) == 'function') protocol_id_reload__RAND__();
				if(typeof(doc_template_id_reload__RAND__) == 'function') doc_template_id_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function protocol_id_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#protocol_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_protocol_id__RAND__.value, t: 'Outcoming_Files', f: 'protocol_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="protocol_id"]').val(resp.results[0].id);
							$j('[id=protocol_id-container-readonly__RAND__]').html('<span class="match-text" id="protocol_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Protocol_view_parent]').hide(); } else { $j('.btn[id=Protocol_view_parent]').show(); }


							if(typeof(protocol_id_update_autofills__RAND__) == 'function') protocol_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Outcoming_Files', f: 'protocol_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_protocol_id__RAND__.value = e.added.id;
				AppGini.current_protocol_id__RAND__.text = e.added.text;
				$j('[name="protocol_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Protocol_view_parent]').hide(); } else { $j('.btn[id=Protocol_view_parent]').show(); }


				if(typeof(protocol_id_update_autofills__RAND__) == 'function') protocol_id_update_autofills__RAND__();
			});

			if(!$j("#protocol_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_protocol_id__RAND__.value, t: 'Outcoming_Files', f: 'protocol_id' },
					success: function(resp) {
						$j('[name="protocol_id"]').val(resp.results[0].id);
						$j('[id=protocol_id-container-readonly__RAND__]').html('<span class="match-text" id="protocol_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Protocol_view_parent]').hide(); } else { $j('.btn[id=Protocol_view_parent]').show(); }

						if(typeof(protocol_id_update_autofills__RAND__) == 'function') protocol_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_protocol_id__RAND__.value, t: 'Outcoming_Files', f: 'protocol_id' },
				success: function(resp) {
					$j('[id=protocol_id-container__RAND__], [id=protocol_id-container-readonly__RAND__]').html('<span class="match-text" id="protocol_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Protocol_view_parent]').hide(); } else { $j('.btn[id=Protocol_view_parent]').show(); }

					if(typeof(protocol_id_update_autofills__RAND__) == 'function') protocol_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function doc_template_id_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#doc_template_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_doc_template_id__RAND__.value, t: 'Outcoming_Files', f: 'doc_template_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="doc_template_id"]').val(resp.results[0].id);
							$j('[id=doc_template_id-container-readonly__RAND__]').html('<span class="match-text" id="doc_template_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Documents_templates_view_parent]').hide(); } else { $j('.btn[id=Documents_templates_view_parent]').show(); }


							if(typeof(doc_template_id_update_autofills__RAND__) == 'function') doc_template_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Outcoming_Files', f: 'doc_template_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_doc_template_id__RAND__.value = e.added.id;
				AppGini.current_doc_template_id__RAND__.text = e.added.text;
				$j('[name="doc_template_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Documents_templates_view_parent]').hide(); } else { $j('.btn[id=Documents_templates_view_parent]').show(); }


				if(typeof(doc_template_id_update_autofills__RAND__) == 'function') doc_template_id_update_autofills__RAND__();
			});

			if(!$j("#doc_template_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_doc_template_id__RAND__.value, t: 'Outcoming_Files', f: 'doc_template_id' },
					success: function(resp) {
						$j('[name="doc_template_id"]').val(resp.results[0].id);
						$j('[id=doc_template_id-container-readonly__RAND__]').html('<span class="match-text" id="doc_template_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Documents_templates_view_parent]').hide(); } else { $j('.btn[id=Documents_templates_view_parent]').show(); }

						if(typeof(doc_template_id_update_autofills__RAND__) == 'function') doc_template_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_doc_template_id__RAND__.value, t: 'Outcoming_Files', f: 'doc_template_id' },
				success: function(resp) {
					$j('[id=doc_template_id-container__RAND__], [id=doc_template_id-container-readonly__RAND__]').html('<span class="match-text" id="doc_template_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Documents_templates_view_parent]').hide(); } else { $j('.btn[id=Documents_templates_view_parent]').show(); }

					if(typeof(doc_template_id_update_autofills__RAND__) == 'function') doc_template_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Outcoming_Files_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Outcoming_Files_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', '&#917;&#958;&#949;&#961;&#967;&#972;&#956;&#949;&#957;&#959;', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Outcoming_Files_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Outcoming_Files_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Outcoming_Files_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#protocol_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#protocol_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#title').replaceWith('<div class=\"form-control-static\" id=\"title\">' + (jQuery('#title').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#doc_template_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#doc_template_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#hex_doc').replaceWith('<div class=\"form-control-static\" id=\"hex_doc\">' + (jQuery('#hex_doc').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#file').replaceWith('<div class=\"form-control-static\" id=\"file\">' + (jQuery('#file').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#file, #file-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(protocol_id)%%>', $combo_protocol_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(protocol_id)%%>', $combo_protocol_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(protocol_id)%%>', urlencode($combo_protocol_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(doc_template_id)%%>', $combo_doc_template_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(doc_template_id)%%>', $combo_doc_template_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(doc_template_id)%%>', urlencode($combo_doc_template_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['protocol_id' => ['Protocol', '&#913;&#961;. &#928;&#961;&#969;&#964;&#959;&#954;&#972;&#955;&#955;&#959;&#965;'], 'doc_template_id' => ['Documents_templates', '&#904;&#947;&#947;&#961;&#945;&#966;&#959; &#945;&#960;&#972; &#960;&#961;&#972;&#964;&#965;&#960;&#959;'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(protocol_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(title)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(doc_template_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hex_doc)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(file)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="file" id="file" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="5120000" style="max-width: calc(100% - 1.5rem);" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($AllowUpdate && $row['file'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(file)%%>', '<input type="checkbox" name="file_remove" id="file_remove" value="1"> <label for="file_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(file)%%>', '', $templateCode);
	}

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(protocol_id)%%>', safe_html($urow['protocol_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(protocol_id)%%>', html_attr($row['protocol_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(protocol_id)%%>', urlencode($urow['protocol_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(title)%%>', safe_html($urow['title']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(title)%%>', html_attr($row['title']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(title)%%>', urlencode($urow['title']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(doc_template_id)%%>', safe_html($urow['doc_template_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(doc_template_id)%%>', html_attr($row['doc_template_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc_template_id)%%>', urlencode($urow['doc_template_id']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(hex_doc)%%>', safe_html($urow['hex_doc']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(hex_doc)%%>', safe_html($urow['hex_doc'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(hex_doc)%%>', urlencode($urow['hex_doc']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(file)%%>', safe_html($urow['file']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(file)%%>', html_attr($row['file']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(file)%%>', urlencode($urow['file']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(protocol_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(protocol_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(title)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(title)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(doc_template_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc_template_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hex_doc)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hex_doc)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(file)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(file)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('fileEdit')) { document.getElementById('fileEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('fileEditLink')) { document.getElementById('fileEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Outcoming_Files');
	if($selected_id) {
		$jdata = get_joined_record('Outcoming_Files', $selected_id);
		if($jdata === false) $jdata = get_defaults('Outcoming_Files');
		$rdata = $row;
	}
	$templateCode .= loadView('Outcoming_Files-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Outcoming_Files_dv
	if(function_exists('Outcoming_Files_dv')) {
		$args = [];
		Outcoming_Files_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}