<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Projectors_timetable.php');
	include_once(__DIR__ . '/Projectors_timetable_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Projectors_timetable');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Projectors_timetable';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Projectors_timetable`.`id`" => "id",
		"IF(    CHAR_LENGTH(`TeachersName1`.`Name`), CONCAT_WS('',   `TeachersName1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "teacher_id",
		"if(`Projectors_timetable`.`date`,date_format(`Projectors_timetable`.`date`,'%d-%m-%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "hour_id",
		"IF(    CHAR_LENGTH(`Projectors1`.`name`), CONCAT_WS('',   `Projectors1`.`name`), '') /* &#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962; */" => "projector_id",
		"`Projectors_timetable`.`star_time`" => "star_time",
		"`Projectors_timetable`.`end_time`" => "end_time",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Projectors_timetable`.`id`',
		2 => '`TeachersName1`.`Name`',
		3 => '`Projectors_timetable`.`date`',
		4 => '`Hours1`.`name`',
		5 => '`Projectors1`.`name`',
		6 => '`Projectors_timetable`.`star_time`',
		7 => '`Projectors_timetable`.`end_time`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Projectors_timetable`.`id`" => "id",
		"IF(    CHAR_LENGTH(`TeachersName1`.`Name`), CONCAT_WS('',   `TeachersName1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "teacher_id",
		"if(`Projectors_timetable`.`date`,date_format(`Projectors_timetable`.`date`,'%d-%m-%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "hour_id",
		"IF(    CHAR_LENGTH(`Projectors1`.`name`), CONCAT_WS('',   `Projectors1`.`name`), '') /* &#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962; */" => "projector_id",
		"`Projectors_timetable`.`star_time`" => "star_time",
		"`Projectors_timetable`.`end_time`" => "end_time",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Projectors_timetable`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`TeachersName1`.`Name`), CONCAT_WS('',   `TeachersName1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;",
		"`Projectors_timetable`.`date`" => "&#919;&#956;&#941;&#961;&#945;",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "&#911;&#961;&#945;",
		"IF(    CHAR_LENGTH(`Projectors1`.`name`), CONCAT_WS('',   `Projectors1`.`name`), '') /* &#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962; */" => "&#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962;",
		"`Projectors_timetable`.`star_time`" => "Star time",
		"`Projectors_timetable`.`end_time`" => "End time",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Projectors_timetable`.`id`" => "id",
		"IF(    CHAR_LENGTH(`TeachersName1`.`Name`), CONCAT_WS('',   `TeachersName1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "teacher_id",
		"if(`Projectors_timetable`.`date`,date_format(`Projectors_timetable`.`date`,'%d-%m-%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "hour_id",
		"IF(    CHAR_LENGTH(`Projectors1`.`name`), CONCAT_WS('',   `Projectors1`.`name`), '') /* &#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962; */" => "projector_id",
		"`Projectors_timetable`.`star_time`" => "star_time",
		"`Projectors_timetable`.`end_time`" => "end_time",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['teacher_id' => '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;', 'hour_id' => '&#911;&#961;&#945;', 'projector_id' => '&#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962;', ];

	$x->QueryFrom = "`Projectors_timetable` LEFT JOIN `TeachersName` as TeachersName1 ON `TeachersName1`.`id`=`Projectors_timetable`.`teacher_id` LEFT JOIN `Hours` as Hours1 ON `Hours1`.`id`=`Projectors_timetable`.`hour_id` LEFT JOIN `Projectors` as Projectors1 ON `Projectors1`.`id`=`Projectors_timetable`.`projector_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Projectors_timetable_view.php';
	$x->TableTitle = '&#935;&#961;&#959;&#957;&#959;&#955;&#972;&#947;&#953;&#959; &#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#969;&#957; ';
	$x->TableIcon = 'resources/table_icons/timetable.png';
	$x->PrimaryKey = '`Projectors_timetable`.`id`';
	$x->DefaultSortField = '`Projectors_timetable`.`date`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;', '&#919;&#956;&#941;&#961;&#945;', '&#911;&#961;&#945;', '&#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962;', ];
	$x->ColFieldName = ['teacher_id', 'date', 'hour_id', 'projector_id', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Projectors_timetable_templateTV.html';
	$x->SelectedTemplate = 'templates/Projectors_timetable_templateTVS.html';
	$x->TemplateDV = 'templates/Projectors_timetable_templateDV.html';
	$x->TemplateDVP = 'templates/Projectors_timetable_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Projectors_timetable_init
	$render = true;
	if(function_exists('Projectors_timetable_init')) {
		$args = [];
		$render = Projectors_timetable_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Projectors_timetable_header
	$headerCode = '';
	if(function_exists('Projectors_timetable_header')) {
		$args = [];
		$headerCode = Projectors_timetable_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Projectors_timetable_footer
	$footerCode = '';
	if(function_exists('Projectors_timetable_footer')) {
		$args = [];
		$footerCode = Projectors_timetable_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
