<?php

// Data functions (insert, update, delete, form) for table Protocol

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Protocol_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Protocol');
	if(!$arrPerm['insert']) return false;

	$data = [
		'receipt_date' => Request::dateComponents('receipt_date', ''),
		'doc_number' => Request::val('doc_number', ''),
		'place' => Request::val('place', ''),
		'authority_issuing' => Request::val('authority_issuing', ''),
		'date_issuing' => Request::dateComponents('date_issuing', ''),
		'summary_incoming' => br2nl(Request::val('summary_incoming', '')),
		'to_whom' => Request::val('to_whom', ''),
		'authority_outcoming' => Request::val('authority_outcoming', ''),
		'summary_outcoming' => br2nl(Request::val('summary_outcoming', '')),
		'outcoming_date' => Request::dateComponents('outcoming_date', ''),
		'processing_date' => Request::dateComponents('processing_date', ''),
		'folder_id' => Request::lookup('folder_id', ''),
		'subfolder_id' => Request::lookup('subfolder_id', ''),
		'comments' => br2nl(Request::val('comments', '')),
	];


	// hook: Protocol_before_insert
	if(function_exists('Protocol_before_insert')) {
		$args = [];
		if(!Protocol_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Protocol', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Protocol', $recID, calculated_fields()['Protocol']);

	// hook: Protocol_after_insert
	if(function_exists('Protocol_after_insert')) {
		$res = sql("SELECT * FROM `Protocol` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Protocol_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Protocol', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Protocol_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Protocol_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Protocol_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Protocol', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Protocol_before_delete
	if(function_exists('Protocol_before_delete')) {
		$args = [];
		if(!Protocol_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Incoming_Files
	$res = sql("SELECT `id` FROM `Protocol` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Incoming_Files` WHERE `protocol_id`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Incoming_Files', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Incoming_Files', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Protocol_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Protocol_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Outcoming_Files
	$res = sql("SELECT `id` FROM `Protocol` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Outcoming_Files` WHERE `protocol_id`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Outcoming_Files', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Outcoming_Files', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Protocol_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Protocol_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Protocol` WHERE `id`='{$selected_id}'", $eo);

	// hook: Protocol_after_delete
	if(function_exists('Protocol_after_delete')) {
		$args = [];
		Protocol_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Protocol' AND `pkValue`='{$selected_id}'", $eo);
}

function Protocol_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Protocol', $selected_id, 'edit')) return false;

	$data = [
		'receipt_date' => Request::dateComponents('receipt_date', ''),
		'doc_number' => Request::val('doc_number', ''),
		'place' => Request::val('place', ''),
		'authority_issuing' => Request::val('authority_issuing', ''),
		'date_issuing' => Request::dateComponents('date_issuing', ''),
		'summary_incoming' => br2nl(Request::val('summary_incoming', '')),
		'to_whom' => Request::val('to_whom', ''),
		'authority_outcoming' => Request::val('authority_outcoming', ''),
		'summary_outcoming' => br2nl(Request::val('summary_outcoming', '')),
		'outcoming_date' => Request::dateComponents('outcoming_date', ''),
		'processing_date' => Request::dateComponents('processing_date', ''),
		'folder_id' => Request::lookup('folder_id', ''),
		'subfolder_id' => Request::lookup('subfolder_id', ''),
		'comments' => br2nl(Request::val('comments', '')),
	];

	// get existing values
	$old_data = getRecord('Protocol', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Protocol_before_update
	if(function_exists('Protocol_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Protocol_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Protocol', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Protocol_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Protocol', $data['selectedID'], calculated_fields()['Protocol']);

	// hook: Protocol_after_update
	if(function_exists('Protocol_after_update')) {
		$res = sql("SELECT * FROM `Protocol` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Protocol_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Protocol', $selected_id);
}

function Protocol_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Protocol');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_folder_id = Request::val('filterer_folder_id');
	$filterer_subfolder_id = Request::val('filterer_subfolder_id');

	// populate filterers, starting from children to grand-parents
	if($filterer_subfolder_id && !$filterer_folder_id) $filterer_folder_id = sqlValue("select folder_id from Subfolders where id='" . makeSafe($filterer_subfolder_id) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: receipt_date
	$combo_receipt_date = new DateCombo;
	$combo_receipt_date->DateFormat = "dmy";
	$combo_receipt_date->MinYear = defined('Protocol.receipt_date.MinYear') ? constant('Protocol.receipt_date.MinYear') : 1900;
	$combo_receipt_date->MaxYear = defined('Protocol.receipt_date.MaxYear') ? constant('Protocol.receipt_date.MaxYear') : 2100;
	$combo_receipt_date->DefaultDate = parseMySQLDate('', '');
	$combo_receipt_date->MonthNames = $Translation['month names'];
	$combo_receipt_date->NamePrefix = 'receipt_date';
	// combobox: date_issuing
	$combo_date_issuing = new DateCombo;
	$combo_date_issuing->DateFormat = "dmy";
	$combo_date_issuing->MinYear = defined('Protocol.date_issuing.MinYear') ? constant('Protocol.date_issuing.MinYear') : 1900;
	$combo_date_issuing->MaxYear = defined('Protocol.date_issuing.MaxYear') ? constant('Protocol.date_issuing.MaxYear') : 2100;
	$combo_date_issuing->DefaultDate = parseMySQLDate('', '');
	$combo_date_issuing->MonthNames = $Translation['month names'];
	$combo_date_issuing->NamePrefix = 'date_issuing';
	// combobox: outcoming_date
	$combo_outcoming_date = new DateCombo;
	$combo_outcoming_date->DateFormat = "dmy";
	$combo_outcoming_date->MinYear = defined('Protocol.outcoming_date.MinYear') ? constant('Protocol.outcoming_date.MinYear') : 1900;
	$combo_outcoming_date->MaxYear = defined('Protocol.outcoming_date.MaxYear') ? constant('Protocol.outcoming_date.MaxYear') : 2100;
	$combo_outcoming_date->DefaultDate = parseMySQLDate('', '');
	$combo_outcoming_date->MonthNames = $Translation['month names'];
	$combo_outcoming_date->NamePrefix = 'outcoming_date';
	// combobox: processing_date
	$combo_processing_date = new DateCombo;
	$combo_processing_date->DateFormat = "dmy";
	$combo_processing_date->MinYear = defined('Protocol.processing_date.MinYear') ? constant('Protocol.processing_date.MinYear') : 1900;
	$combo_processing_date->MaxYear = defined('Protocol.processing_date.MaxYear') ? constant('Protocol.processing_date.MaxYear') : 2100;
	$combo_processing_date->DefaultDate = parseMySQLDate('', '');
	$combo_processing_date->MonthNames = $Translation['month names'];
	$combo_processing_date->NamePrefix = 'processing_date';
	// combobox: folder_id
	$combo_folder_id = new DataCombo;
	// combobox: subfolder_id, filterable by: folder_id
	$combo_subfolder_id = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('Protocol', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Protocol', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Protocol', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Protocol` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Protocol_view.php', false);
		}
		$combo_receipt_date->DefaultDate = $row['receipt_date'];
		$combo_date_issuing->DefaultDate = $row['date_issuing'];
		$combo_outcoming_date->DefaultDate = $row['outcoming_date'];
		$combo_processing_date->DefaultDate = $row['processing_date'];
		$combo_folder_id->SelectedData = $row['folder_id'];
		$combo_subfolder_id->SelectedData = $row['subfolder_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_folder_id->SelectedData = $filterer_folder_id;
		$combo_subfolder_id->SelectedData = $filterer_subfolder_id;
	}
	$combo_folder_id->HTML = '<span id="folder_id-container' . $rnd1 . '"></span><input type="hidden" name="folder_id" id="folder_id' . $rnd1 . '" value="' . html_attr($combo_folder_id->SelectedData) . '">';
	$combo_folder_id->MatchText = '<span id="folder_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="folder_id" id="folder_id' . $rnd1 . '" value="' . html_attr($combo_folder_id->SelectedData) . '">';
	$combo_subfolder_id->HTML = '<span id="subfolder_id-container' . $rnd1 . '"></span><input type="hidden" name="subfolder_id" id="subfolder_id' . $rnd1 . '" value="' . html_attr($combo_subfolder_id->SelectedData) . '">';
	$combo_subfolder_id->MatchText = '<span id="subfolder_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="subfolder_id" id="subfolder_id' . $rnd1 . '" value="' . html_attr($combo_subfolder_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_folder_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['folder_id'] : htmlspecialchars($filterer_folder_id, ENT_QUOTES)); ?>"};
		AppGini.current_subfolder_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['subfolder_id'] : htmlspecialchars($filterer_subfolder_id, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(folder_id_reload__RAND__) == 'function') folder_id_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(subfolder_id_reload__RAND__) == \'function\') subfolder_id_reload__RAND__(AppGini.current_folder_id__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function folder_id_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#folder_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_folder_id__RAND__.value, t: 'Protocol', f: 'folder_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="folder_id"]').val(resp.results[0].id);
							$j('[id=folder_id-container-readonly__RAND__]').html('<span class="match-text" id="folder_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Folders_view_parent]').hide(); } else { $j('.btn[id=Folders_view_parent]').show(); }

						if(typeof(subfolder_id_reload__RAND__) == 'function') subfolder_id_reload__RAND__(AppGini.current_folder_id__RAND__.value);

							if(typeof(folder_id_update_autofills__RAND__) == 'function') folder_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Protocol', f: 'folder_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_folder_id__RAND__.value = e.added.id;
				AppGini.current_folder_id__RAND__.text = e.added.text;
				$j('[name="folder_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Folders_view_parent]').hide(); } else { $j('.btn[id=Folders_view_parent]').show(); }

						if(typeof(subfolder_id_reload__RAND__) == 'function') subfolder_id_reload__RAND__(AppGini.current_folder_id__RAND__.value);

				if(typeof(folder_id_update_autofills__RAND__) == 'function') folder_id_update_autofills__RAND__();
			});

			if(!$j("#folder_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_folder_id__RAND__.value, t: 'Protocol', f: 'folder_id' },
					success: function(resp) {
						$j('[name="folder_id"]').val(resp.results[0].id);
						$j('[id=folder_id-container-readonly__RAND__]').html('<span class="match-text" id="folder_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Folders_view_parent]').hide(); } else { $j('.btn[id=Folders_view_parent]').show(); }

						if(typeof(folder_id_update_autofills__RAND__) == 'function') folder_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_folder_id__RAND__.value, t: 'Protocol', f: 'folder_id' },
				success: function(resp) {
					$j('[id=folder_id-container__RAND__], [id=folder_id-container-readonly__RAND__]').html('<span class="match-text" id="folder_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Folders_view_parent]').hide(); } else { $j('.btn[id=Folders_view_parent]').show(); }

					if(typeof(folder_id_update_autofills__RAND__) == 'function') folder_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function subfolder_id_reload__RAND__(filterer_folder_id) {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#subfolder_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_folder_id: filterer_folder_id, id: AppGini.current_subfolder_id__RAND__.value, t: 'Protocol', f: 'subfolder_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="subfolder_id"]').val(resp.results[0].id);
							$j('[id=subfolder_id-container-readonly__RAND__]').html('<span class="match-text" id="subfolder_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Subfolders_view_parent]').hide(); } else { $j('.btn[id=Subfolders_view_parent]').show(); }


							if(typeof(subfolder_id_update_autofills__RAND__) == 'function') subfolder_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_folder_id: filterer_folder_id, s: term, p: page, t: 'Protocol', f: 'subfolder_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_subfolder_id__RAND__.value = e.added.id;
				AppGini.current_subfolder_id__RAND__.text = e.added.text;
				$j('[name="subfolder_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Subfolders_view_parent]').hide(); } else { $j('.btn[id=Subfolders_view_parent]').show(); }


				if(typeof(subfolder_id_update_autofills__RAND__) == 'function') subfolder_id_update_autofills__RAND__();
			});

			if(!$j("#subfolder_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_subfolder_id__RAND__.value, t: 'Protocol', f: 'subfolder_id' },
					success: function(resp) {
						$j('[name="subfolder_id"]').val(resp.results[0].id);
						$j('[id=subfolder_id-container-readonly__RAND__]').html('<span class="match-text" id="subfolder_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Subfolders_view_parent]').hide(); } else { $j('.btn[id=Subfolders_view_parent]').show(); }

						if(typeof(subfolder_id_update_autofills__RAND__) == 'function') subfolder_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_subfolder_id__RAND__.value, t: 'Protocol', f: 'subfolder_id' },
				success: function(resp) {
					$j('[id=subfolder_id-container__RAND__], [id=subfolder_id-container-readonly__RAND__]').html('<span class="match-text" id="subfolder_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Subfolders_view_parent]').hide(); } else { $j('.btn[id=Subfolders_view_parent]').show(); }

					if(typeof(subfolder_id_update_autofills__RAND__) == 'function') subfolder_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Protocol_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Protocol_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', '&#917;&#953;&#963;&#945;&#947;&#969;&#947;&#942; &#917;&#947;&#947;&#961;&#940;&#966;&#959;&#965;', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Protocol_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Protocol_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Protocol_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#receipt_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#receipt_dateDay, #receipt_dateMonth, #receipt_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#doc_number').replaceWith('<div class=\"form-control-static\" id=\"doc_number\">' + (jQuery('#doc_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#place').replaceWith('<div class=\"form-control-static\" id=\"place\">' + (jQuery('#place').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#authority_issuing').replaceWith('<div class=\"form-control-static\" id=\"authority_issuing\">' + (jQuery('#authority_issuing').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#date_issuing').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#date_issuingDay, #date_issuingMonth, #date_issuingYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#summary_incoming').replaceWith('<div class=\"form-control-static\" id=\"summary_incoming\">' + (jQuery('#summary_incoming').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#to_whom').replaceWith('<div class=\"form-control-static\" id=\"to_whom\">' + (jQuery('#to_whom').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#authority_outcoming').replaceWith('<div class=\"form-control-static\" id=\"authority_outcoming\">' + (jQuery('#authority_outcoming').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#summary_outcoming').replaceWith('<div class=\"form-control-static\" id=\"summary_outcoming\">' + (jQuery('#summary_outcoming').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#outcoming_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#outcoming_dateDay, #outcoming_dateMonth, #outcoming_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#processing_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#processing_dateDay, #processing_dateMonth, #processing_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#folder_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#folder_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#subfolder_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#subfolder_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#comments').replaceWith('<div class=\"form-control-static\" id=\"comments\">' + (jQuery('#comments').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(receipt_date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_receipt_date->GetHTML(true) . '</div>' : 
			$combo_receipt_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(receipt_date)%%>', $combo_receipt_date->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(date_issuing)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date_issuing->GetHTML(true) . '</div>' : 
			$combo_date_issuing->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date_issuing)%%>', $combo_date_issuing->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(outcoming_date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_outcoming_date->GetHTML(true) . '</div>' : 
			$combo_outcoming_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(outcoming_date)%%>', $combo_outcoming_date->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(processing_date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_processing_date->GetHTML(true) . '</div>' : 
			$combo_processing_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(processing_date)%%>', $combo_processing_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(folder_id)%%>', $combo_folder_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(folder_id)%%>', $combo_folder_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(folder_id)%%>', urlencode($combo_folder_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(subfolder_id)%%>', $combo_subfolder_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(subfolder_id)%%>', $combo_subfolder_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(subfolder_id)%%>', urlencode($combo_subfolder_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['folder_id' => ['Folders', '&#934;&#940;&#954;&#949;&#955;&#959;&#962; &#913;&#961;&#967;&#949;&#943;&#959;&#965;'], 'subfolder_id' => ['Subfolders', '&#933;&#960;&#959;&#966;&#940;&#954;&#949;&#955;&#959;&#962; &#913;&#961;&#967;&#949;&#943;&#959;&#965;'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(serial_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(receipt_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(doc_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(place)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(authority_issuing)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_issuing)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(summary_incoming)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(to_whom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(authority_outcoming)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(summary_outcoming)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(outcoming_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(processing_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(folder_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subfolder_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comments)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(serial_number)%%>', safe_html($urow['serial_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serial_number)%%>', urlencode($urow['serial_number']), $templateCode);
		$templateCode = str_replace('<%%VALUE(receipt_date)%%>', app_datetime($row['receipt_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(receipt_date)%%>', urlencode(app_datetime($urow['receipt_date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(doc_number)%%>', safe_html($urow['doc_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(doc_number)%%>', html_attr($row['doc_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc_number)%%>', urlencode($urow['doc_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(place)%%>', safe_html($urow['place']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(place)%%>', html_attr($row['place']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(place)%%>', urlencode($urow['place']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(authority_issuing)%%>', safe_html($urow['authority_issuing']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(authority_issuing)%%>', html_attr($row['authority_issuing']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(authority_issuing)%%>', urlencode($urow['authority_issuing']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_issuing)%%>', app_datetime($row['date_issuing']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_issuing)%%>', urlencode(app_datetime($urow['date_issuing'])), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(summary_incoming)%%>', safe_html($urow['summary_incoming']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(summary_incoming)%%>', safe_html($urow['summary_incoming'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(summary_incoming)%%>', urlencode($urow['summary_incoming']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(to_whom)%%>', safe_html($urow['to_whom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(to_whom)%%>', html_attr($row['to_whom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(to_whom)%%>', urlencode($urow['to_whom']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(authority_outcoming)%%>', safe_html($urow['authority_outcoming']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(authority_outcoming)%%>', html_attr($row['authority_outcoming']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(authority_outcoming)%%>', urlencode($urow['authority_outcoming']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(summary_outcoming)%%>', safe_html($urow['summary_outcoming']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(summary_outcoming)%%>', safe_html($urow['summary_outcoming'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(summary_outcoming)%%>', urlencode($urow['summary_outcoming']), $templateCode);
		$templateCode = str_replace('<%%VALUE(outcoming_date)%%>', app_datetime($row['outcoming_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(outcoming_date)%%>', urlencode(app_datetime($urow['outcoming_date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(processing_date)%%>', app_datetime($row['processing_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(processing_date)%%>', urlencode(app_datetime($urow['processing_date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(folder_id)%%>', safe_html($urow['folder_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(folder_id)%%>', html_attr($row['folder_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(folder_id)%%>', urlencode($urow['folder_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subfolder_id)%%>', safe_html($urow['subfolder_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subfolder_id)%%>', html_attr($row['subfolder_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subfolder_id)%%>', urlencode($urow['subfolder_id']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(comments)%%>', safe_html($urow['comments']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(comments)%%>', safe_html($urow['comments'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(comments)%%>', urlencode($urow['comments']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(serial_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serial_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(receipt_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(receipt_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(doc_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(place)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(place)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(authority_issuing)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(authority_issuing)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_issuing)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_issuing)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(summary_incoming)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(summary_incoming)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(to_whom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(to_whom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(authority_outcoming)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(authority_outcoming)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(summary_outcoming)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(summary_outcoming)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(outcoming_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(outcoming_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(processing_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(processing_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(folder_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(folder_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subfolder_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subfolder_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(comments)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comments)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Protocol');
	if($selected_id) {
		$jdata = get_joined_record('Protocol', $selected_id);
		if($jdata === false) $jdata = get_defaults('Protocol');
		$rdata = $row;
	}
	$templateCode .= loadView('Protocol-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Protocol_dv
	if(function_exists('Protocol_dv')) {
		$args = [];
		Protocol_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}