<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Subfolders.php');
	include_once(__DIR__ . '/Subfolders_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Subfolders');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Subfolders';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Subfolders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Folders1`.`folder`), CONCAT_WS('',   `Folders1`.`folder`), '') /* &#934;&#940;&#954;&#949;&#955;&#959;&#962; */" => "folder_id",
		"`Subfolders`.`subfolder`" => "subfolder",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Subfolders`.`id`',
		2 => '`Folders1`.`folder`',
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Subfolders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Folders1`.`folder`), CONCAT_WS('',   `Folders1`.`folder`), '') /* &#934;&#940;&#954;&#949;&#955;&#959;&#962; */" => "folder_id",
		"`Subfolders`.`subfolder`" => "subfolder",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Subfolders`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Folders1`.`folder`), CONCAT_WS('',   `Folders1`.`folder`), '') /* &#934;&#940;&#954;&#949;&#955;&#959;&#962; */" => "&#934;&#940;&#954;&#949;&#955;&#959;&#962;",
		"`Subfolders`.`subfolder`" => "&#933;&#960;&#959;&#966;&#940;&#954;&#949;&#955;&#959;&#962;",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Subfolders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Folders1`.`folder`), CONCAT_WS('',   `Folders1`.`folder`), '') /* &#934;&#940;&#954;&#949;&#955;&#959;&#962; */" => "folder_id",
		"`Subfolders`.`subfolder`" => "subfolder",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['folder_id' => '&#934;&#940;&#954;&#949;&#955;&#959;&#962;', ];

	$x->QueryFrom = "`Subfolders` LEFT JOIN `Folders` as Folders1 ON `Folders1`.`id`=`Subfolders`.`folder_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Subfolders_view.php';
	$x->TableTitle = '&#933;&#960;&#959;&#966;&#940;&#954;&#949;&#955;&#959;&#953;';
	$x->TableIcon = 'resources/table_icons/folders_explorer.png';
	$x->PrimaryKey = '`Subfolders`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['&#934;&#940;&#954;&#949;&#955;&#959;&#962;', '&#933;&#960;&#959;&#966;&#940;&#954;&#949;&#955;&#959;&#962;', ];
	$x->ColFieldName = ['folder_id', 'subfolder', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Subfolders_templateTV.html';
	$x->SelectedTemplate = 'templates/Subfolders_templateTVS.html';
	$x->TemplateDV = 'templates/Subfolders_templateDV.html';
	$x->TemplateDVP = 'templates/Subfolders_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Subfolders_init
	$render = true;
	if(function_exists('Subfolders_init')) {
		$args = [];
		$render = Subfolders_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Subfolders_header
	$headerCode = '';
	if(function_exists('Subfolders_header')) {
		$args = [];
		$headerCode = Subfolders_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Subfolders_footer
	$footerCode = '';
	if(function_exists('Subfolders_footer')) {
		$args = [];
		$footerCode = Subfolders_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
