<?php

// Data functions (insert, update, delete, form) for table Teachers

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Teachers_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Teachers');
	if(!$arrPerm['insert']) return false;

	$data = [
		'SectorID' => Request::lookup('SectorID', ''),
		'Name' => Request::val('Name', ''),
		'Name2' => Request::lookup('Name2', ''),
		'Placement' => Request::val('Placement', ''),
		'Assumption_Date' => Request::dateComponents('Assumption_Date', ''),
		'Mandatory_Hours' => Request::val('Mandatory_Hours', '0'),
		'Main_Sector' => Request::val('Main_Sector', ''),
	];


	// hook: Teachers_before_insert
	if(function_exists('Teachers_before_insert')) {
		$args = [];
		if(!Teachers_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Teachers', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Teachers', $recID, calculated_fields()['Teachers']);

	// hook: Teachers_after_insert
	if(function_exists('Teachers_after_insert')) {
		$res = sql("SELECT * FROM `Teachers` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Teachers_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Teachers', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Teachers_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Teachers_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Teachers_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Teachers', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Teachers_before_delete
	if(function_exists('Teachers_before_delete')) {
		$args = [];
		if(!Teachers_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Assignments
	$res = sql("SELECT `id` FROM `Teachers` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Assignments` WHERE `TeacherID`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Assignments', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Assignments', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Teachers_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Teachers_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Assignments
	$res = sql("SELECT `id` FROM `Teachers` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Assignments` WHERE `TeacherID2`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Assignments', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Assignments', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Teachers_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Teachers_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Tests
	$res = sql("SELECT `id` FROM `Teachers` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Tests` WHERE `teacher_id`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Tests', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Tests', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Teachers_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Teachers_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Teachers` WHERE `id`='{$selected_id}'", $eo);

	// hook: Teachers_after_delete
	if(function_exists('Teachers_after_delete')) {
		$args = [];
		Teachers_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Teachers' AND `pkValue`='{$selected_id}'", $eo);
}

function Teachers_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Teachers', $selected_id, 'edit')) return false;

	$data = [
		'SectorID' => Request::lookup('SectorID', ''),
		'Name' => Request::val('Name', ''),
		'Name2' => Request::lookup('Name2', ''),
		'Placement' => Request::val('Placement', ''),
		'Assumption_Date' => Request::dateComponents('Assumption_Date', ''),
		'Mandatory_Hours' => Request::val('Mandatory_Hours', ''),
		'Main_Sector' => Request::val('Main_Sector', ''),
	];

	// get existing values
	$old_data = getRecord('Teachers', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Teachers_before_update
	if(function_exists('Teachers_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Teachers_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Teachers', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Teachers_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Teachers', $data['selectedID'], calculated_fields()['Teachers']);

	// hook: Teachers_after_update
	if(function_exists('Teachers_after_update')) {
		$res = sql("SELECT * FROM `Teachers` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Teachers_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Teachers', $selected_id);
}

function Teachers_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Teachers');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_SectorID = Request::val('filterer_SectorID');
	$filterer_Name2 = Request::val('filterer_Name2');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: SectorID
	$combo_SectorID = new DataCombo;
	// combobox: Name2
	$combo_Name2 = new DataCombo;
	// combobox: Placement
	$combo_Placement = new Combo;
	$combo_Placement->ListType = 0;
	$combo_Placement->MultipleSeparator = ', ';
	$combo_Placement->ListBoxHeight = 10;
	$combo_Placement->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Teachers.Placement.csv')) {
		$Placement_data = addslashes(implode('', @file(__DIR__ . '/hooks/Teachers.Placement.csv')));
		$combo_Placement->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Placement_data))));
		$combo_Placement->ListData = $combo_Placement->ListItem;
	} else {
		$combo_Placement->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("&#927;&#929;&#915;&#913;&#925;&#921;&#922;&#919;;;&#913;&#925;&#913;&#928;&#923;&#919;&#929;&#937;&#932;&#919;&#931;;;&#913;&#928;&#927;&#931;&#928;&#913;&#931;&#919;;;&#916;&#921;&#913;&#920;&#917;&#931;&#919;"))));
		$combo_Placement->ListData = $combo_Placement->ListItem;
	}
	$combo_Placement->SelectName = 'Placement';
	// combobox: Assumption_Date
	$combo_Assumption_Date = new DateCombo;
	$combo_Assumption_Date->DateFormat = "dmy";
	$combo_Assumption_Date->MinYear = defined('Teachers.Assumption_Date.MinYear') ? constant('Teachers.Assumption_Date.MinYear') : 1900;
	$combo_Assumption_Date->MaxYear = defined('Teachers.Assumption_Date.MaxYear') ? constant('Teachers.Assumption_Date.MaxYear') : 2100;
	$combo_Assumption_Date->DefaultDate = parseMySQLDate('', '');
	$combo_Assumption_Date->MonthNames = $Translation['month names'];
	$combo_Assumption_Date->NamePrefix = 'Assumption_Date';

	if($selected_id) {
		if(!check_record_permission('Teachers', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Teachers', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Teachers', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Teachers` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Teachers_view.php', false);
		}
		$combo_SectorID->SelectedData = $row['SectorID'];
		$combo_Name2->SelectedData = $row['Name2'];
		$combo_Placement->SelectedData = $row['Placement'];
		$combo_Assumption_Date->DefaultDate = $row['Assumption_Date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_SectorID->SelectedData = $filterer_SectorID;
		$combo_Name2->SelectedData = $filterer_Name2;
		$combo_Placement->SelectedText = (isset($filterField[1]) && $filterField[1] == '6' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_SectorID->HTML = '<span id="SectorID-container' . $rnd1 . '"></span><input type="hidden" name="SectorID" id="SectorID' . $rnd1 . '" value="' . html_attr($combo_SectorID->SelectedData) . '">';
	$combo_SectorID->MatchText = '<span id="SectorID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="SectorID" id="SectorID' . $rnd1 . '" value="' . html_attr($combo_SectorID->SelectedData) . '">';
	$combo_Name2->HTML = '<span id="Name2-container' . $rnd1 . '"></span><input type="hidden" name="Name2" id="Name2' . $rnd1 . '" value="' . html_attr($combo_Name2->SelectedData) . '">';
	$combo_Name2->MatchText = '<span id="Name2-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Name2" id="Name2' . $rnd1 . '" value="' . html_attr($combo_Name2->SelectedData) . '">';
	$combo_Placement->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_SectorID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['SectorID'] : htmlspecialchars($filterer_SectorID, ENT_QUOTES)); ?>"};
		AppGini.current_Name2__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Name2'] : htmlspecialchars($filterer_Name2, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(SectorID_reload__RAND__) == 'function') SectorID_reload__RAND__();
				if(typeof(Name2_reload__RAND__) == 'function') Name2_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function SectorID_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#SectorID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_SectorID__RAND__.value, t: 'Teachers', f: 'SectorID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="SectorID"]').val(resp.results[0].id);
							$j('[id=SectorID-container-readonly__RAND__]').html('<span class="match-text" id="SectorID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Sectors_view_parent]').hide(); } else { $j('.btn[id=Sectors_view_parent]').show(); }


							if(typeof(SectorID_update_autofills__RAND__) == 'function') SectorID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Teachers', f: 'SectorID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_SectorID__RAND__.value = e.added.id;
				AppGini.current_SectorID__RAND__.text = e.added.text;
				$j('[name="SectorID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Sectors_view_parent]').hide(); } else { $j('.btn[id=Sectors_view_parent]').show(); }


				if(typeof(SectorID_update_autofills__RAND__) == 'function') SectorID_update_autofills__RAND__();
			});

			if(!$j("#SectorID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_SectorID__RAND__.value, t: 'Teachers', f: 'SectorID' },
					success: function(resp) {
						$j('[name="SectorID"]').val(resp.results[0].id);
						$j('[id=SectorID-container-readonly__RAND__]').html('<span class="match-text" id="SectorID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Sectors_view_parent]').hide(); } else { $j('.btn[id=Sectors_view_parent]').show(); }

						if(typeof(SectorID_update_autofills__RAND__) == 'function') SectorID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_SectorID__RAND__.value, t: 'Teachers', f: 'SectorID' },
				success: function(resp) {
					$j('[id=SectorID-container__RAND__], [id=SectorID-container-readonly__RAND__]').html('<span class="match-text" id="SectorID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Sectors_view_parent]').hide(); } else { $j('.btn[id=Sectors_view_parent]').show(); }

					if(typeof(SectorID_update_autofills__RAND__) == 'function') SectorID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Name2_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#Name2-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Name2__RAND__.value, t: 'Teachers', f: 'Name2' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Name2"]').val(resp.results[0].id);
							$j('[id=Name2-container-readonly__RAND__]').html('<span class="match-text" id="Name2-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TeachersName_view_parent]').hide(); } else { $j('.btn[id=TeachersName_view_parent]').show(); }


							if(typeof(Name2_update_autofills__RAND__) == 'function') Name2_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Teachers', f: 'Name2' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Name2__RAND__.value = e.added.id;
				AppGini.current_Name2__RAND__.text = e.added.text;
				$j('[name="Name2"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TeachersName_view_parent]').hide(); } else { $j('.btn[id=TeachersName_view_parent]').show(); }


				if(typeof(Name2_update_autofills__RAND__) == 'function') Name2_update_autofills__RAND__();
			});

			if(!$j("#Name2-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Name2__RAND__.value, t: 'Teachers', f: 'Name2' },
					success: function(resp) {
						$j('[name="Name2"]').val(resp.results[0].id);
						$j('[id=Name2-container-readonly__RAND__]').html('<span class="match-text" id="Name2-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TeachersName_view_parent]').hide(); } else { $j('.btn[id=TeachersName_view_parent]').show(); }

						if(typeof(Name2_update_autofills__RAND__) == 'function') Name2_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Name2__RAND__.value, t: 'Teachers', f: 'Name2' },
				success: function(resp) {
					$j('[id=Name2-container__RAND__], [id=Name2-container-readonly__RAND__]').html('<span class="match-text" id="Name2-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TeachersName_view_parent]').hide(); } else { $j('.btn[id=TeachersName_view_parent]').show(); }

					if(typeof(Name2_update_autofills__RAND__) == 'function') Name2_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Teachers_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Teachers_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Teachers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Teachers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Teachers_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#SectorID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#SectorID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Name').replaceWith('<div class=\"form-control-static\" id=\"Name\">' + (jQuery('#Name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Name2').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Name2_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Placement').replaceWith('<div class=\"form-control-static\" id=\"Placement\">' + (jQuery('#Placement').val() || '') + '</div>'); jQuery('#Placement-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Assumption_Date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Assumption_DateDay, #Assumption_DateMonth, #Assumption_DateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Mandatory_Hours').replaceWith('<div class=\"form-control-static\" id=\"Mandatory_Hours\">' + (jQuery('#Mandatory_Hours').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Main_Sector').replaceWith('<div class=\"form-control-static\" id=\"Main_Sector\">' + (jQuery('#Main_Sector').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(SectorID)%%>', $combo_SectorID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(SectorID)%%>', $combo_SectorID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(SectorID)%%>', urlencode($combo_SectorID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Name2)%%>', $combo_Name2->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Name2)%%>', $combo_Name2->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Name2)%%>', urlencode($combo_Name2->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Placement)%%>', $combo_Placement->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Placement)%%>', $combo_Placement->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(Assumption_Date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_Assumption_Date->GetHTML(true) . '</div>' : 
			$combo_Assumption_Date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Assumption_Date)%%>', $combo_Assumption_Date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['SectorID' => ['Sectors', '&#932;&#959;&#956;&#941;&#945;&#962;'], 'Name2' => ['TeachersName', 'Name2'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SectorID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Name_Sector)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Name2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Placement)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Assumption_Date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Mandatory_Hours)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Main_Sector)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Assigned_Hours_Theory)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Assigned_Hours_Lab)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Assigned_Hours)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Diff)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SectorID)%%>', safe_html($urow['SectorID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SectorID)%%>', html_attr($row['SectorID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SectorID)%%>', urlencode($urow['SectorID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Name_Sector)%%>', safe_html($urow['Name_Sector']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name_Sector)%%>', urlencode($urow['Name_Sector']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', safe_html($urow['Name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', html_attr($row['Name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode($urow['Name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Name2)%%>', safe_html($urow['Name2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Name2)%%>', html_attr($row['Name2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name2)%%>', urlencode($urow['Name2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Placement)%%>', safe_html($urow['Placement']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Placement)%%>', html_attr($row['Placement']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Placement)%%>', urlencode($urow['Placement']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assumption_Date)%%>', app_datetime($row['Assumption_Date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assumption_Date)%%>', urlencode(app_datetime($urow['Assumption_Date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Mandatory_Hours)%%>', safe_html($urow['Mandatory_Hours']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Mandatory_Hours)%%>', html_attr($row['Mandatory_Hours']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Mandatory_Hours)%%>', urlencode($urow['Mandatory_Hours']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Main_Sector)%%>', safe_html($urow['Main_Sector']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Main_Sector)%%>', html_attr($row['Main_Sector']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Main_Sector)%%>', urlencode($urow['Main_Sector']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned_Hours_Theory)%%>', safe_html($urow['Assigned_Hours_Theory']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned_Hours_Theory)%%>', urlencode($urow['Assigned_Hours_Theory']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned_Hours_Lab)%%>', safe_html($urow['Assigned_Hours_Lab']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned_Hours_Lab)%%>', urlencode($urow['Assigned_Hours_Lab']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned_Hours)%%>', safe_html($urow['Assigned_Hours']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned_Hours)%%>', urlencode($urow['Assigned_Hours']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Diff)%%>', safe_html($urow['Diff']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Diff)%%>', urlencode($urow['Diff']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SectorID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SectorID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Name_Sector)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name_Sector)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Name2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Placement)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Placement)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assumption_Date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assumption_Date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Mandatory_Hours)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Mandatory_Hours)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Main_Sector)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Main_Sector)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned_Hours_Theory)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned_Hours_Theory)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned_Hours_Lab)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned_Hours_Lab)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned_Hours)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned_Hours)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Diff)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Diff)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Teachers');
	if($selected_id) {
		$jdata = get_joined_record('Teachers', $selected_id);
		if($jdata === false) $jdata = get_defaults('Teachers');
		$rdata = $row;
	}
	$templateCode .= loadView('Teachers-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Teachers_dv
	if(function_exists('Teachers_dv')) {
		$args = [];
		Teachers_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}