<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/TeachersName.php');
	include_once(__DIR__ . '/TeachersName_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('TeachersName');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'TeachersName';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`TeachersName`.`id`" => "id",
		"`TeachersName`.`Name`" => "Name",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`TeachersName`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`TeachersName`.`id`" => "id",
		"`TeachersName`.`Name`" => "Name",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`TeachersName`.`id`" => "ID",
		"`TeachersName`.`Name`" => "&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`TeachersName`.`id`" => "id",
		"`TeachersName`.`Name`" => "Name",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`TeachersName` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'TeachersName_view.php';
	$x->TableTitle = '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#959;&#943;';
	$x->TableIcon = 'resources/table_icons/Teacher.png';
	$x->PrimaryKey = '`TeachersName`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;', ];
	$x->ColFieldName = ['Name', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/TeachersName_templateTV.html';
	$x->SelectedTemplate = 'templates/TeachersName_templateTVS.html';
	$x->TemplateDV = 'templates/TeachersName_templateDV.html';
	$x->TemplateDVP = 'templates/TeachersName_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: TeachersName_init
	$render = true;
	if(function_exists('TeachersName_init')) {
		$args = [];
		$render = TeachersName_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: TeachersName_header
	$headerCode = '';
	if(function_exists('TeachersName_header')) {
		$args = [];
		$headerCode = TeachersName_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: TeachersName_footer
	$footerCode = '';
	if(function_exists('TeachersName_footer')) {
		$args = [];
		$footerCode = TeachersName_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
