<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Tests.php');
	include_once(__DIR__ . '/Tests_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Tests');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Tests';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Tests`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Teachers1`.`Name`), CONCAT_WS('',   `Teachers1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "teacher_id",
		"IF(    CHAR_LENGTH(`Assignments1`.`LessonName`), CONCAT_WS('',   `Assignments1`.`LessonName`), '') /* &#924;&#940;&#952;&#951;&#956;&#945; */" => "assignments_id",
		"if(`Tests`.`date`,date_format(`Tests`.`date`,'%d-%m-%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "hour_id",
		"`Tests`.`file`" => "file",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Tests`.`id`',
		2 => '`Teachers1`.`Name`',
		3 => '`Assignments1`.`LessonName`',
		4 => '`Tests`.`date`',
		5 => '`Hours1`.`name`',
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Tests`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Teachers1`.`Name`), CONCAT_WS('',   `Teachers1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "teacher_id",
		"IF(    CHAR_LENGTH(`Assignments1`.`LessonName`), CONCAT_WS('',   `Assignments1`.`LessonName`), '') /* &#924;&#940;&#952;&#951;&#956;&#945; */" => "assignments_id",
		"if(`Tests`.`date`,date_format(`Tests`.`date`,'%d-%m-%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "hour_id",
		"`Tests`.`file`" => "file",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Tests`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Teachers1`.`Name`), CONCAT_WS('',   `Teachers1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;",
		"IF(    CHAR_LENGTH(`Assignments1`.`LessonName`), CONCAT_WS('',   `Assignments1`.`LessonName`), '') /* &#924;&#940;&#952;&#951;&#956;&#945; */" => "&#924;&#940;&#952;&#951;&#956;&#945;",
		"`Tests`.`date`" => "&#919;&#956;&#941;&#961;&#945;",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "&#911;&#961;&#945;",
		"`Tests`.`file`" => "&#916;&#953;&#945;&#947;&#974;&#957;&#953;&#963;&#956;&#945;",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Tests`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Teachers1`.`Name`), CONCAT_WS('',   `Teachers1`.`Name`), '') /* &#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; */" => "teacher_id",
		"IF(    CHAR_LENGTH(`Assignments1`.`LessonName`), CONCAT_WS('',   `Assignments1`.`LessonName`), '') /* &#924;&#940;&#952;&#951;&#956;&#945; */" => "assignments_id",
		"if(`Tests`.`date`,date_format(`Tests`.`date`,'%d-%m-%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Hours1`.`name`), CONCAT_WS('',   `Hours1`.`name`), '') /* &#911;&#961;&#945; */" => "hour_id",
		"`Tests`.`file`" => "file",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['teacher_id' => '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;', 'assignments_id' => '&#924;&#940;&#952;&#951;&#956;&#945;', 'hour_id' => '&#911;&#961;&#945;', ];

	$x->QueryFrom = "`Tests` LEFT JOIN `Teachers` as Teachers1 ON `Teachers1`.`id`=`Tests`.`teacher_id` LEFT JOIN `Assignments` as Assignments1 ON `Assignments1`.`id`=`Tests`.`assignments_id` LEFT JOIN `Hours` as Hours1 ON `Hours1`.`id`=`Tests`.`hour_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Tests_view.php';
	$x->TableTitle = '&#916;&#953;&#945;&#947;&#969;&#957;&#943;&#963;&#956;&#945;&#964;&#945;';
	$x->TableIcon = 'resources/table_icons/align_center.png';
	$x->PrimaryKey = '`Tests`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;', '&#924;&#940;&#952;&#951;&#956;&#945;', '&#919;&#956;&#941;&#961;&#945;', '&#911;&#961;&#945;', '&#916;&#953;&#945;&#947;&#974;&#957;&#953;&#963;&#956;&#945;', ];
	$x->ColFieldName = ['teacher_id', 'assignments_id', 'date', 'hour_id', 'file', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Tests_templateTV.html';
	$x->SelectedTemplate = 'templates/Tests_templateTVS.html';
	$x->TemplateDV = 'templates/Tests_templateDV.html';
	$x->TemplateDVP = 'templates/Tests_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Tests_init
	$render = true;
	if(function_exists('Tests_init')) {
		$args = [];
		$render = Tests_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Tests_header
	$headerCode = '';
	if(function_exists('Tests_header')) {
		$args = [];
		$headerCode = Tests_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Tests_footer
	$footerCode = '';
	if(function_exists('Tests_footer')) {
		$args = [];
		$footerCode = Tests_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
