<?php

// Data functions (insert, update, delete, form) for table Assignments

// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

function Assignments_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Assignments');
	if(!$arrPerm['insert']) return false;

	$data = [
		'ClassID' => Request::lookup('ClassID', ''),
		'LessonID' => Request::lookup('LessonID', ''),
		'TeacherID' => Request::lookup('TeacherID', ''),
		'TeacherID2' => Request::lookup('TeacherID2', ''),
	];

	if($data['ClassID'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#932;&#956;&#942;&#956;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['LessonID'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#924;&#940;&#952;&#951;&#956;&#945;:': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Assignments_before_insert
	if(function_exists('Assignments_before_insert')) {
		$args = [];
		if(!Assignments_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Assignments', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Assignments', $recID, calculated_fields()['Assignments']);

	// hook: Assignments_after_insert
	if(function_exists('Assignments_after_insert')) {
		$res = sql("SELECT * FROM `Assignments` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Assignments_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Assignments', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Assignments_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Assignments_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Assignments_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Assignments', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Assignments_before_delete
	if(function_exists('Assignments_before_delete')) {
		$args = [];
		if(!Assignments_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Assignments` WHERE `id`='{$selected_id}'", $eo);

	// hook: Assignments_after_delete
	if(function_exists('Assignments_after_delete')) {
		$args = [];
		Assignments_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Assignments' AND `pkValue`='{$selected_id}'", $eo);
}

function Assignments_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Assignments', $selected_id, 'edit')) return false;

	$data = [
		'ClassID' => Request::lookup('ClassID', ''),
		'LessonID' => Request::lookup('LessonID', ''),
		'TeacherID' => Request::lookup('TeacherID', ''),
		'TeacherID2' => Request::lookup('TeacherID2', ''),
		'datetime' => parseCode('<%%editingDateTime%%>', false, true),
	];

	if($data['ClassID'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#932;&#956;&#942;&#956;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['LessonID'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#924;&#940;&#952;&#951;&#956;&#945;:': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Assignments', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Assignments_before_update
	if(function_exists('Assignments_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Assignments_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Assignments', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Assignments_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Assignments', $data['selectedID'], calculated_fields()['Assignments']);

	// hook: Assignments_after_update
	if(function_exists('Assignments_after_update')) {
		$res = sql("SELECT * FROM `Assignments` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Assignments_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Assignments' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Assignments_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Assignments');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_ClassID = Request::val('filterer_ClassID');
	$filterer_LessonID = Request::val('filterer_LessonID');
	$filterer_TeacherID = Request::val('filterer_TeacherID');
	$filterer_TeacherID2 = Request::val('filterer_TeacherID2');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: ClassID
	$combo_ClassID = new DataCombo;
	// combobox: LessonID
	$combo_LessonID = new DataCombo;
	// combobox: TeacherID
	$combo_TeacherID = new DataCombo;
	// combobox: TeacherID2
	$combo_TeacherID2 = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('Assignments', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Assignments', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Assignments', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Assignments` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Assignments_view.php', false);
		}
		$combo_ClassID->SelectedData = $row['ClassID'];
		$combo_LessonID->SelectedData = $row['LessonID'];
		$combo_TeacherID->SelectedData = $row['TeacherID'];
		$combo_TeacherID2->SelectedData = $row['TeacherID2'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_ClassID->SelectedData = $filterer_ClassID;
		$combo_LessonID->SelectedData = $filterer_LessonID;
		$combo_TeacherID->SelectedData = $filterer_TeacherID;
		$combo_TeacherID2->SelectedData = $filterer_TeacherID2;
	}
	$combo_ClassID->HTML = '<span id="ClassID-container' . $rnd1 . '"></span><input type="hidden" name="ClassID" id="ClassID' . $rnd1 . '" value="' . html_attr($combo_ClassID->SelectedData) . '">';
	$combo_ClassID->MatchText = '<span id="ClassID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ClassID" id="ClassID' . $rnd1 . '" value="' . html_attr($combo_ClassID->SelectedData) . '">';
	$combo_LessonID->HTML = '<span id="LessonID-container' . $rnd1 . '"></span><input type="hidden" name="LessonID" id="LessonID' . $rnd1 . '" value="' . html_attr($combo_LessonID->SelectedData) . '">';
	$combo_LessonID->MatchText = '<span id="LessonID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="LessonID" id="LessonID' . $rnd1 . '" value="' . html_attr($combo_LessonID->SelectedData) . '">';
	$combo_TeacherID->HTML = '<span id="TeacherID-container' . $rnd1 . '"></span><input type="hidden" name="TeacherID" id="TeacherID' . $rnd1 . '" value="' . html_attr($combo_TeacherID->SelectedData) . '">';
	$combo_TeacherID->MatchText = '<span id="TeacherID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="TeacherID" id="TeacherID' . $rnd1 . '" value="' . html_attr($combo_TeacherID->SelectedData) . '">';
	$combo_TeacherID2->HTML = '<span id="TeacherID2-container' . $rnd1 . '"></span><input type="hidden" name="TeacherID2" id="TeacherID2' . $rnd1 . '" value="' . html_attr($combo_TeacherID2->SelectedData) . '">';
	$combo_TeacherID2->MatchText = '<span id="TeacherID2-container-readonly' . $rnd1 . '"></span><input type="hidden" name="TeacherID2" id="TeacherID2' . $rnd1 . '" value="' . html_attr($combo_TeacherID2->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_ClassID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ClassID'] : htmlspecialchars($filterer_ClassID, ENT_QUOTES)); ?>"};
		AppGini.current_LessonID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['LessonID'] : htmlspecialchars($filterer_LessonID, ENT_QUOTES)); ?>"};
		AppGini.current_TeacherID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['TeacherID'] : htmlspecialchars($filterer_TeacherID, ENT_QUOTES)); ?>"};
		AppGini.current_TeacherID2__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['TeacherID2'] : htmlspecialchars($filterer_TeacherID2, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(ClassID_reload__RAND__) == 'function') ClassID_reload__RAND__();
				if(typeof(LessonID_reload__RAND__) == 'function') LessonID_reload__RAND__();
				if(typeof(TeacherID_reload__RAND__) == 'function') TeacherID_reload__RAND__();
				if(typeof(TeacherID2_reload__RAND__) == 'function') TeacherID2_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function ClassID_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#ClassID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_ClassID__RAND__.value, t: 'Assignments', f: 'ClassID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ClassID"]').val(resp.results[0].id);
							$j('[id=ClassID-container-readonly__RAND__]').html('<span class="match-text" id="ClassID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Classes_view_parent]').hide(); } else { $j('.btn[id=Classes_view_parent]').show(); }


							if(typeof(ClassID_update_autofills__RAND__) == 'function') ClassID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Assignments', f: 'ClassID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_ClassID__RAND__.value = e.added.id;
				AppGini.current_ClassID__RAND__.text = e.added.text;
				$j('[name="ClassID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Classes_view_parent]').hide(); } else { $j('.btn[id=Classes_view_parent]').show(); }


				if(typeof(ClassID_update_autofills__RAND__) == 'function') ClassID_update_autofills__RAND__();
			});

			if(!$j("#ClassID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ClassID__RAND__.value, t: 'Assignments', f: 'ClassID' },
					success: function(resp) {
						$j('[name="ClassID"]').val(resp.results[0].id);
						$j('[id=ClassID-container-readonly__RAND__]').html('<span class="match-text" id="ClassID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Classes_view_parent]').hide(); } else { $j('.btn[id=Classes_view_parent]').show(); }

						if(typeof(ClassID_update_autofills__RAND__) == 'function') ClassID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ClassID__RAND__.value, t: 'Assignments', f: 'ClassID' },
				success: function(resp) {
					$j('[id=ClassID-container__RAND__], [id=ClassID-container-readonly__RAND__]').html('<span class="match-text" id="ClassID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Classes_view_parent]').hide(); } else { $j('.btn[id=Classes_view_parent]').show(); }

					if(typeof(ClassID_update_autofills__RAND__) == 'function') ClassID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function LessonID_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#LessonID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_LessonID__RAND__.value, t: 'Assignments', f: 'LessonID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="LessonID"]').val(resp.results[0].id);
							$j('[id=LessonID-container-readonly__RAND__]').html('<span class="match-text" id="LessonID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lessons_view_parent]').hide(); } else { $j('.btn[id=Lessons_view_parent]').show(); }


							if(typeof(LessonID_update_autofills__RAND__) == 'function') LessonID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Assignments', f: 'LessonID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_LessonID__RAND__.value = e.added.id;
				AppGini.current_LessonID__RAND__.text = e.added.text;
				$j('[name="LessonID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lessons_view_parent]').hide(); } else { $j('.btn[id=Lessons_view_parent]').show(); }


				if(typeof(LessonID_update_autofills__RAND__) == 'function') LessonID_update_autofills__RAND__();
			});

			if(!$j("#LessonID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_LessonID__RAND__.value, t: 'Assignments', f: 'LessonID' },
					success: function(resp) {
						$j('[name="LessonID"]').val(resp.results[0].id);
						$j('[id=LessonID-container-readonly__RAND__]').html('<span class="match-text" id="LessonID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lessons_view_parent]').hide(); } else { $j('.btn[id=Lessons_view_parent]').show(); }

						if(typeof(LessonID_update_autofills__RAND__) == 'function') LessonID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_LessonID__RAND__.value, t: 'Assignments', f: 'LessonID' },
				success: function(resp) {
					$j('[id=LessonID-container__RAND__], [id=LessonID-container-readonly__RAND__]').html('<span class="match-text" id="LessonID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lessons_view_parent]').hide(); } else { $j('.btn[id=Lessons_view_parent]').show(); }

					if(typeof(LessonID_update_autofills__RAND__) == 'function') LessonID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function TeacherID_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#TeacherID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_TeacherID__RAND__.value, t: 'Assignments', f: 'TeacherID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="TeacherID"]').val(resp.results[0].id);
							$j('[id=TeacherID-container-readonly__RAND__]').html('<span class="match-text" id="TeacherID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }


							if(typeof(TeacherID_update_autofills__RAND__) == 'function') TeacherID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Assignments', f: 'TeacherID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_TeacherID__RAND__.value = e.added.id;
				AppGini.current_TeacherID__RAND__.text = e.added.text;
				$j('[name="TeacherID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }


				if(typeof(TeacherID_update_autofills__RAND__) == 'function') TeacherID_update_autofills__RAND__();
			});

			if(!$j("#TeacherID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_TeacherID__RAND__.value, t: 'Assignments', f: 'TeacherID' },
					success: function(resp) {
						$j('[name="TeacherID"]').val(resp.results[0].id);
						$j('[id=TeacherID-container-readonly__RAND__]').html('<span class="match-text" id="TeacherID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }

						if(typeof(TeacherID_update_autofills__RAND__) == 'function') TeacherID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_TeacherID__RAND__.value, t: 'Assignments', f: 'TeacherID' },
				success: function(resp) {
					$j('[id=TeacherID-container__RAND__], [id=TeacherID-container-readonly__RAND__]').html('<span class="match-text" id="TeacherID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }

					if(typeof(TeacherID_update_autofills__RAND__) == 'function') TeacherID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function TeacherID2_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#TeacherID2-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_TeacherID2__RAND__.value, t: 'Assignments', f: 'TeacherID2' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="TeacherID2"]').val(resp.results[0].id);
							$j('[id=TeacherID2-container-readonly__RAND__]').html('<span class="match-text" id="TeacherID2-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }


							if(typeof(TeacherID2_update_autofills__RAND__) == 'function') TeacherID2_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Assignments', f: 'TeacherID2' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_TeacherID2__RAND__.value = e.added.id;
				AppGini.current_TeacherID2__RAND__.text = e.added.text;
				$j('[name="TeacherID2"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }


				if(typeof(TeacherID2_update_autofills__RAND__) == 'function') TeacherID2_update_autofills__RAND__();
			});

			if(!$j("#TeacherID2-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_TeacherID2__RAND__.value, t: 'Assignments', f: 'TeacherID2' },
					success: function(resp) {
						$j('[name="TeacherID2"]').val(resp.results[0].id);
						$j('[id=TeacherID2-container-readonly__RAND__]').html('<span class="match-text" id="TeacherID2-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }

						if(typeof(TeacherID2_update_autofills__RAND__) == 'function') TeacherID2_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_TeacherID2__RAND__.value, t: 'Assignments', f: 'TeacherID2' },
				success: function(resp) {
					$j('[id=TeacherID2-container__RAND__], [id=TeacherID2-container-readonly__RAND__]').html('<span class="match-text" id="TeacherID2-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }

					if(typeof(TeacherID2_update_autofills__RAND__) == 'function') TeacherID2_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Assignments_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Assignments_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', '&#913;&#957;&#940;&#952;&#949;&#963;&#951;', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Assignments_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Assignments_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Assignments_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#ClassID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ClassID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#LessonID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#LessonID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#TeacherID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#TeacherID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#TeacherID2').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#TeacherID2_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(ClassID)%%>', $combo_ClassID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ClassID)%%>', $combo_ClassID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ClassID)%%>', urlencode($combo_ClassID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(LessonID)%%>', $combo_LessonID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(LessonID)%%>', $combo_LessonID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(LessonID)%%>', urlencode($combo_LessonID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(TeacherID)%%>', $combo_TeacherID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(TeacherID)%%>', $combo_TeacherID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(TeacherID)%%>', urlencode($combo_TeacherID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(TeacherID2)%%>', $combo_TeacherID2->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(TeacherID2)%%>', $combo_TeacherID2->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(TeacherID2)%%>', urlencode($combo_TeacherID2->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['ClassID' => ['Classes', '&#932;&#956;&#942;&#956;&#945;'], 'LessonID' => ['Lessons', '&#924;&#940;&#952;&#951;&#956;&#945;:'], 'TeacherID' => ['Teachers', '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; &#913;'], 'TeacherID2' => ['Teachers', '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962; &#914;'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ClassID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(LessonID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(LessonName)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Lesson_A_Assignment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Lesson_B_Assignment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Lesson_C_Assignment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(LessonType)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(LessonHours)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TeacherID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TeacherID2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(datetime)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ClassID)%%>', safe_html($urow['ClassID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ClassID)%%>', html_attr($row['ClassID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ClassID)%%>', urlencode($urow['ClassID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(LessonID)%%>', safe_html($urow['LessonID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(LessonID)%%>', html_attr($row['LessonID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonID)%%>', urlencode($urow['LessonID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonName)%%>', safe_html($urow['LessonName']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonName)%%>', urlencode($urow['LessonName']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lesson_A_Assignment)%%>', safe_html($urow['Lesson_A_Assignment']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lesson_A_Assignment)%%>', urlencode($urow['Lesson_A_Assignment']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lesson_B_Assignment)%%>', safe_html($urow['Lesson_B_Assignment']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lesson_B_Assignment)%%>', urlencode($urow['Lesson_B_Assignment']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lesson_C_Assignment)%%>', safe_html($urow['Lesson_C_Assignment']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lesson_C_Assignment)%%>', urlencode($urow['Lesson_C_Assignment']), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonType)%%>', safe_html($urow['LessonType']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonType)%%>', urlencode($urow['LessonType']), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonHours)%%>', safe_html($urow['LessonHours']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonHours)%%>', urlencode($urow['LessonHours']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(TeacherID)%%>', safe_html($urow['TeacherID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(TeacherID)%%>', html_attr($row['TeacherID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TeacherID)%%>', urlencode($urow['TeacherID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(TeacherID2)%%>', safe_html($urow['TeacherID2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(TeacherID2)%%>', html_attr($row['TeacherID2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TeacherID2)%%>', urlencode($urow['TeacherID2']), $templateCode);
		$templateCode = str_replace('<%%VALUE(datetime)%%>', app_datetime($row['datetime'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(datetime)%%>', urlencode(app_datetime($urow['datetime'], 'dt')), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ClassID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ClassID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonName)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonName)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lesson_A_Assignment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lesson_A_Assignment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lesson_B_Assignment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lesson_B_Assignment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lesson_C_Assignment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lesson_C_Assignment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonType)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonType)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(LessonHours)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LessonHours)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TeacherID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TeacherID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TeacherID2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TeacherID2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(datetime)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(datetime)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Assignments');
	if($selected_id) {
		$jdata = get_joined_record('Assignments', $selected_id);
		if($jdata === false) $jdata = get_defaults('Assignments');
		$rdata = $row;
	}
	$templateCode .= loadView('Assignments-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Assignments_dv
	if(function_exists('Assignments_dv')) {
		$args = [];
		Assignments_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}