<?php
	$dbServer = 'localhost';
	$dbUsername = 'r130181pau_paul';
	$dbPassword = 'Ig@2o793w';
	$dbDatabase = 'r130181pau_assignments';
	$dbPort = '3306';
	$appURI = 'assignments';
	$host = '6epal-esp-thess.gr';

	$adminConfig = [
		'adminUsername' => "admin",
		'adminPassword' => "\$2y\$10\$u.2J6A/b.bcfUpoPRIi/M.0rliavdSINdQgSmZDFKZ/I9cHKKRtta",
		'notifyAdminNewMembers' => "0",
		'defaultSignUp' => "1",
		'anonymousGroup' => "anonymous",
		'anonymousMember' => "guest",
		'groupsPerPage' => "10",
		'membersPerPage' => "10",
		'recordsPerPage' => "10",
		'custom1' => "Full Name",
		'custom2' => "Address",
		'custom3' => "City",
		'custom4' => "State",
		'MySQLDateFormat' => "%d/%m/%Y",
		'PHPDateFormat' => "j/n/Y",
		'PHPDateTimeFormat' => "d/m/Y, h:i a",
		'senderName' => "Membership management",
		'senderEmail' => "paulgai@yahoo.gr",
		'approvalSubject' => "Your membership is now approved",
		'approvalMessage' => "Dear member,\r\n\r\nYour membership is now approved by the admin. You can log in to your account here:\r\nhttp://6epal-esp-thess.gr/assignments\r\n\r\nRegards,\r\nAdmin",
		'hide_twitter_feed' => "1",
		'maintenance_mode_message' => "<b>Our website is currently down for maintenance</b><br>\r\nWe expect to be back in a couple hours. Thanks for your patience.",
		'mail_function' => "mail",
		'smtp_server' => "",
		'smtp_encryption' => "",
		'smtp_port' => "25",
		'smtp_user' => "",
		'smtp_pass' => "",
		'googleAPIKey' => "",
		'baseUploadPath' => "images",
	];