<?php

// Data functions (insert, update, delete, form) for table Projectors_timetable

// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

function Projectors_timetable_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Projectors_timetable');
	if(!$arrPerm['insert']) return false;

	$data = [
		'teacher_id' => Request::lookup('teacher_id', ''),
		'date' => Request::dateComponents('date', ''),
		'hour_id' => Request::lookup('hour_id', ''),
		'projector_id' => Request::lookup('projector_id', ''),
	];

	if($data['teacher_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['date'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#919;&#956;&#941;&#961;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['hour_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#911;&#961;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Projectors_timetable_before_insert
	if(function_exists('Projectors_timetable_before_insert')) {
		$args = [];
		if(!Projectors_timetable_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Projectors_timetable', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Projectors_timetable', $recID, calculated_fields()['Projectors_timetable']);

	// hook: Projectors_timetable_after_insert
	if(function_exists('Projectors_timetable_after_insert')) {
		$res = sql("SELECT * FROM `Projectors_timetable` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Projectors_timetable_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Projectors_timetable', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Projectors_timetable_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Projectors_timetable_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Projectors_timetable_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Projectors_timetable', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Projectors_timetable_before_delete
	if(function_exists('Projectors_timetable_before_delete')) {
		$args = [];
		if(!Projectors_timetable_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Projectors_timetable` WHERE `id`='{$selected_id}'", $eo);

	// hook: Projectors_timetable_after_delete
	if(function_exists('Projectors_timetable_after_delete')) {
		$args = [];
		Projectors_timetable_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Projectors_timetable' AND `pkValue`='{$selected_id}'", $eo);
}

function Projectors_timetable_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Projectors_timetable', $selected_id, 'edit')) return false;

	$data = [
		'teacher_id' => Request::lookup('teacher_id', ''),
		'date' => Request::dateComponents('date', ''),
		'hour_id' => Request::lookup('hour_id', ''),
		'projector_id' => Request::lookup('projector_id', ''),
	];

	if($data['teacher_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['date'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#919;&#956;&#941;&#961;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['hour_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#911;&#961;&#945;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Projectors_timetable', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Projectors_timetable_before_update
	if(function_exists('Projectors_timetable_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Projectors_timetable_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Projectors_timetable', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Projectors_timetable_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Projectors_timetable', $data['selectedID'], calculated_fields()['Projectors_timetable']);

	// hook: Projectors_timetable_after_update
	if(function_exists('Projectors_timetable_after_update')) {
		$res = sql("SELECT * FROM `Projectors_timetable` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Projectors_timetable_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Projectors_timetable' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Projectors_timetable_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Projectors_timetable');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_teacher_id = Request::val('filterer_teacher_id');
	$filterer_hour_id = Request::val('filterer_hour_id');
	$filterer_projector_id = Request::val('filterer_projector_id');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: teacher_id
	$combo_teacher_id = new DataCombo;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "dmy";
	$combo_date->MinYear = defined('Projectors_timetable.date.MinYear') ? constant('Projectors_timetable.date.MinYear') : 1900;
	$combo_date->MaxYear = defined('Projectors_timetable.date.MaxYear') ? constant('Projectors_timetable.date.MaxYear') : 2100;
	$combo_date->DefaultDate = parseMySQLDate('', '');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: hour_id
	$combo_hour_id = new DataCombo;
	// combobox: projector_id
	$combo_projector_id = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('Projectors_timetable', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Projectors_timetable', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Projectors_timetable', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Projectors_timetable` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Projectors_timetable_view.php', false);
		}
		$combo_teacher_id->SelectedData = $row['teacher_id'];
		$combo_date->DefaultDate = $row['date'];
		$combo_hour_id->SelectedData = $row['hour_id'];
		$combo_projector_id->SelectedData = $row['projector_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_teacher_id->SelectedData = $filterer_teacher_id;
		$combo_hour_id->SelectedData = $filterer_hour_id;
		$combo_projector_id->SelectedData = $filterer_projector_id;
	}
	$combo_teacher_id->HTML = '<span id="teacher_id-container' . $rnd1 . '"></span><input type="hidden" name="teacher_id" id="teacher_id' . $rnd1 . '" value="' . html_attr($combo_teacher_id->SelectedData) . '">';
	$combo_teacher_id->MatchText = '<span id="teacher_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="teacher_id" id="teacher_id' . $rnd1 . '" value="' . html_attr($combo_teacher_id->SelectedData) . '">';
	$combo_hour_id->HTML = '<span id="hour_id-container' . $rnd1 . '"></span><input type="hidden" name="hour_id" id="hour_id' . $rnd1 . '" value="' . html_attr($combo_hour_id->SelectedData) . '">';
	$combo_hour_id->MatchText = '<span id="hour_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="hour_id" id="hour_id' . $rnd1 . '" value="' . html_attr($combo_hour_id->SelectedData) . '">';
	$combo_projector_id->HTML = '<span id="projector_id-container' . $rnd1 . '"></span><input type="hidden" name="projector_id" id="projector_id' . $rnd1 . '" value="' . html_attr($combo_projector_id->SelectedData) . '">';
	$combo_projector_id->MatchText = '<span id="projector_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="projector_id" id="projector_id' . $rnd1 . '" value="' . html_attr($combo_projector_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_teacher_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['teacher_id'] : htmlspecialchars($filterer_teacher_id, ENT_QUOTES)); ?>"};
		AppGini.current_hour_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['hour_id'] : htmlspecialchars($filterer_hour_id, ENT_QUOTES)); ?>"};
		AppGini.current_projector_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['projector_id'] : htmlspecialchars($filterer_projector_id, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(teacher_id_reload__RAND__) == 'function') teacher_id_reload__RAND__();
				if(typeof(hour_id_reload__RAND__) == 'function') hour_id_reload__RAND__();
				if(typeof(projector_id_reload__RAND__) == 'function') projector_id_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function teacher_id_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#teacher_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_teacher_id__RAND__.value, t: 'Projectors_timetable', f: 'teacher_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="teacher_id"]').val(resp.results[0].id);
							$j('[id=teacher_id-container-readonly__RAND__]').html('<span class="match-text" id="teacher_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }


							if(typeof(teacher_id_update_autofills__RAND__) == 'function') teacher_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Projectors_timetable', f: 'teacher_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_teacher_id__RAND__.value = e.added.id;
				AppGini.current_teacher_id__RAND__.text = e.added.text;
				$j('[name="teacher_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }


				if(typeof(teacher_id_update_autofills__RAND__) == 'function') teacher_id_update_autofills__RAND__();
			});

			if(!$j("#teacher_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_teacher_id__RAND__.value, t: 'Projectors_timetable', f: 'teacher_id' },
					success: function(resp) {
						$j('[name="teacher_id"]').val(resp.results[0].id);
						$j('[id=teacher_id-container-readonly__RAND__]').html('<span class="match-text" id="teacher_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }

						if(typeof(teacher_id_update_autofills__RAND__) == 'function') teacher_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_teacher_id__RAND__.value, t: 'Projectors_timetable', f: 'teacher_id' },
				success: function(resp) {
					$j('[id=teacher_id-container__RAND__], [id=teacher_id-container-readonly__RAND__]').html('<span class="match-text" id="teacher_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_view_parent]').hide(); } else { $j('.btn[id=Teachers_view_parent]').show(); }

					if(typeof(teacher_id_update_autofills__RAND__) == 'function') teacher_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function hour_id_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#hour_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_hour_id__RAND__.value, t: 'Projectors_timetable', f: 'hour_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="hour_id"]').val(resp.results[0].id);
							$j('[id=hour_id-container-readonly__RAND__]').html('<span class="match-text" id="hour_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Hours_view_parent]').hide(); } else { $j('.btn[id=Hours_view_parent]').show(); }


							if(typeof(hour_id_update_autofills__RAND__) == 'function') hour_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Projectors_timetable', f: 'hour_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_hour_id__RAND__.value = e.added.id;
				AppGini.current_hour_id__RAND__.text = e.added.text;
				$j('[name="hour_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Hours_view_parent]').hide(); } else { $j('.btn[id=Hours_view_parent]').show(); }


				if(typeof(hour_id_update_autofills__RAND__) == 'function') hour_id_update_autofills__RAND__();
			});

			if(!$j("#hour_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_hour_id__RAND__.value, t: 'Projectors_timetable', f: 'hour_id' },
					success: function(resp) {
						$j('[name="hour_id"]').val(resp.results[0].id);
						$j('[id=hour_id-container-readonly__RAND__]').html('<span class="match-text" id="hour_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Hours_view_parent]').hide(); } else { $j('.btn[id=Hours_view_parent]').show(); }

						if(typeof(hour_id_update_autofills__RAND__) == 'function') hour_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_hour_id__RAND__.value, t: 'Projectors_timetable', f: 'hour_id' },
				success: function(resp) {
					$j('[id=hour_id-container__RAND__], [id=hour_id-container-readonly__RAND__]').html('<span class="match-text" id="hour_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Hours_view_parent]').hide(); } else { $j('.btn[id=Hours_view_parent]').show(); }

					if(typeof(hour_id_update_autofills__RAND__) == 'function') hour_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function projector_id_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#projector_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_projector_id__RAND__.value, t: 'Projectors_timetable', f: 'projector_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="projector_id"]').val(resp.results[0].id);
							$j('[id=projector_id-container-readonly__RAND__]').html('<span class="match-text" id="projector_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Projectors_view_parent]').hide(); } else { $j('.btn[id=Projectors_view_parent]').show(); }


							if(typeof(projector_id_update_autofills__RAND__) == 'function') projector_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Projectors_timetable', f: 'projector_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_projector_id__RAND__.value = e.added.id;
				AppGini.current_projector_id__RAND__.text = e.added.text;
				$j('[name="projector_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Projectors_view_parent]').hide(); } else { $j('.btn[id=Projectors_view_parent]').show(); }


				if(typeof(projector_id_update_autofills__RAND__) == 'function') projector_id_update_autofills__RAND__();
			});

			if(!$j("#projector_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_projector_id__RAND__.value, t: 'Projectors_timetable', f: 'projector_id' },
					success: function(resp) {
						$j('[name="projector_id"]').val(resp.results[0].id);
						$j('[id=projector_id-container-readonly__RAND__]').html('<span class="match-text" id="projector_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Projectors_view_parent]').hide(); } else { $j('.btn[id=Projectors_view_parent]').show(); }

						if(typeof(projector_id_update_autofills__RAND__) == 'function') projector_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_projector_id__RAND__.value, t: 'Projectors_timetable', f: 'projector_id' },
				success: function(resp) {
					$j('[id=projector_id-container__RAND__], [id=projector_id-container-readonly__RAND__]').html('<span class="match-text" id="projector_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Projectors_view_parent]').hide(); } else { $j('.btn[id=Projectors_view_parent]').show(); }

					if(typeof(projector_id_update_autofills__RAND__) == 'function') projector_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Projectors_timetable_templateDV.html';
	$templateCode = @file_get_contents($template_file);

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Projectors timetable details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Projectors_timetable_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Projectors_timetable_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Projectors_timetable_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#teacher_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#teacher_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#hour_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#hour_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#projector_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#projector_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(teacher_id)%%>', $combo_teacher_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(teacher_id)%%>', $combo_teacher_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(teacher_id)%%>', urlencode($combo_teacher_id->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : 
			$combo_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(hour_id)%%>', $combo_hour_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(hour_id)%%>', $combo_hour_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(hour_id)%%>', urlencode($combo_hour_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(projector_id)%%>', $combo_projector_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(projector_id)%%>', $combo_projector_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(projector_id)%%>', urlencode($combo_projector_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['teacher_id' => ['Teachers', '&#917;&#954;&#960;&#945;&#953;&#948;&#949;&#965;&#964;&#953;&#954;&#972;&#962;'], 'hour_id' => ['Hours', '&#911;&#961;&#945;'], 'projector_id' => ['Projectors', '&#914;&#953;&#957;&#964;&#949;&#959;&#960;&#961;&#959;&#946;&#959;&#955;&#941;&#945;&#962;'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(teacher_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hour_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(projector_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(star_time)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(end_time)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(teacher_id)%%>', safe_html($urow['teacher_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(teacher_id)%%>', html_attr($row['teacher_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(teacher_id)%%>', urlencode($urow['teacher_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', app_datetime($row['date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(app_datetime($urow['date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hour_id)%%>', safe_html($urow['hour_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hour_id)%%>', html_attr($row['hour_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hour_id)%%>', urlencode($urow['hour_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(projector_id)%%>', safe_html($urow['projector_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(projector_id)%%>', html_attr($row['projector_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(projector_id)%%>', urlencode($urow['projector_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(star_time)%%>', safe_html($urow['star_time']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(star_time)%%>', urlencode($urow['star_time']), $templateCode);
		$templateCode = str_replace('<%%VALUE(end_time)%%>', safe_html($urow['end_time']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(end_time)%%>', urlencode($urow['end_time']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(teacher_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(teacher_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hour_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hour_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(projector_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(projector_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(star_time)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(star_time)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(end_time)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(end_time)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Projectors_timetable');
	if($selected_id) {
		$jdata = get_joined_record('Projectors_timetable', $selected_id);
		if($jdata === false) $jdata = get_defaults('Projectors_timetable');
		$rdata = $row;
	}
	$templateCode .= loadView('Projectors_timetable-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Projectors_timetable_dv
	if(function_exists('Projectors_timetable_dv')) {
		$args = [];
		Projectors_timetable_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}